#!/bin/bash

#  Authors     [Robert Meolic (robert@meolic.com)]
#  Revision    [$Revision: 582 $]
#  Date        [$Date: 2020-02-08 16:18:16 +0100 (sob, 08 feb 2020) $]
#
#  Copyright   [
#    This file is part of Biddy.
#    Copyright (C) 2006, 2019 UM FERI, Koroska cesta 46, SI-2000 Maribor, Slovenia
#    Copyright (C) 2019, 2020 Robert Meolic, SI-2000 Maribor, Slovenia
#
#    Biddy is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as
#    published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    Biddy is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public
#    License along with this program; if not, write to the Free
#    Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#    Boston, MA 02110-1301 USA.
#  ]

VERSION=`sed "s|\.|-|g" VERSION`

rm -f "biddy-source-$VERSION.zip"

make purge
make clean

cd ..
zip -o "biddy/biddy-source-$VERSION.zip" biddy/* -x biddy/*.zip -x biddy/*.pdf -x biddy/*.tmp -x biddy/bin/ -x biddy/doxygen/ -x biddy/biddy-studio/ -x biddy/doc/ -x biddy/test/ -x biddy/biddy-example-* -x biddy/distribution/ x biddy/distribution-bddscout/
zip -o "biddy/biddy-source-$VERSION.zip" biddy/biddy-example-*.c biddy/biddy-example-*.h biddy/biddy-example-pp-data.csv
zip -o "biddy/biddy-source-$VERSION.zip" biddy/debian/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/debian/*/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/rpm/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/rpm/*/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/VS/* -x biddy/VS/*.aip -x biddy/VS/*.aiproj
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/* -x biddy/bddscout/*.zip -x biddy/bddscout/ISCAS/ -x biddy/bddscout/bin/ -x biddy/bddscout/test/
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/create/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/scripts/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/debian/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/debian/*/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/rpm/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/rpm/*/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/IFIP/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/IFIP/*/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/BDDTRACES/*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/DICTIONARY/biddy-words*
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddscout/ENCYCLOPEDIA/* -x biddy/bddscout/ENCYCLOPEDIA/*.pdf
zip -o "biddy/biddy-source-$VERSION.zip" biddy/bddview/*
cd biddy

echo ""
echo "*******************"
echo "PACKAGES COMPLETED!"
echo "*******************"
echo ""
