#!/bin/bash

#  Authors     [Robert Meolic (robert@meolic.com)]
#  Revision    [$Revision: 692 $]
#  Date        [$Date: 2024-06-30 18:06:54 +0200 (ned, 30 jun 2024) $]
#
#  Copyright   [
#    This file is part of Biddy.
#    Copyright (C) 2006, 2019 UM FERI, Koroska cesta 46, SI-2000 Maribor, Slovenia
#    Copyright (C) 2019, 2024 Robert Meolic, SI-2000 Maribor, Slovenia
#
#    Biddy is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as
#    published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    Biddy is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public
#    License along with this program; if not, write to the Free
#    Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#    Boston, MA 02110-1301 USA.
#  ]

# use CFLAGS="-m32" to produce 32-bit libs
# use CFLAGS="-m64" to produce 64-bit libs
# leave empty for system default
CFLAGS+=""

NAME="biddy"
VERSION=`sed "s|\.|-|g" VERSION`
OS=`uname | sed "s/_.*//;s/[0-9]//g"`

rm -f "$NAME-bin-$VERSION-$OS.zip"
rm -f "$NAME-$VERSION-$OS.zip"

rm -fr "./$NAME-$VERSION"

make "CFLAGS = $CFLAGS" "BINDIR = ../biddy/$NAME-$VERSION"
make clean "BINDIR = ../biddy/$NAME-$VERSION"

cp COPYING "./$NAME-$VERSION/"
cp CHANGES "./$NAME-$VERSION/"
cp biddy.h "./$NAME-$VERSION/"

echo "Creating $NAME-$VERSION-$OS.zip ..."
zip -y -o "$NAME-$VERSION-$OS.zip" "./$NAME-$VERSION"/* -x "./$NAME-$VERSION"/biddy.h -x "./$NAME-$VERSION"/libbiddy.a -x "./$NAME-$VERSION"/*.so
if [ -e "./$NAME-$VERSION"/libbiddy.so ] && [ ! -L "./$NAME-$VERSION"/libbiddy.so ] ; then
  zip -y -o "$NAME-$VERSION-$OS.zip" "./$NAME-$VERSION"/libbiddy.so
fi

cp biddy-cudd.h biddy-cudd.c "./$NAME-$VERSION/"
cp biddy-example-8queens.c "./$NAME-$VERSION/"
cp biddy-example-independence.c biddy-example-independence-europe.c biddy-example-independence-usa.c biddy-example-independence-test.c "./$NAME-$VERSION/"
cp biddy-example-hanoi.c "./$NAME-$VERSION/"
cp biddy-example-dictionary.c biddy-example-dictman.c biddy-example-dict-common.c biddy-example-dict-common.h "./$NAME-$VERSION/"
cp biddy-example-bra.c "./$NAME-$VERSION/"
cp biddy-example-pp.c biddy-example-pp-data.c biddy-example-pp-data.csv "./$NAME-$VERSION/"

echo "Creating $NAME-dev-$VERSION-$OS.zip ..."
zip -y -o "$NAME-dev-$VERSION-$OS.zip" "./$NAME-$VERSION"/*

rm -fr "./$NAME-$VERSION"

echo ""
echo "*******************"
echo "PACKAGES COMPLETED!"
echo "*******************"
echo ""
