/**CHeaderFile*************************************************************
  PackageName [Bdd Scout]
  Synopsis    [Bdd Scout]

  FileName    [bddscoutDecls.h]
  Revision    [$Revision: 253 $]
  Date        [$Date: 2017-03-20 09:03:47 +0100 (pon, 20 mar 2017) $]
  Authors     [Robert Meolic (robert.meolic@um.si)]
  Description [Generated by genStubs.tcl, see http://wiki.tcl.tk/3358]
  SeeAlso     [bddscout.h, bddscout.decls, bddscoutStubInit.c, bddscoutStubLib.c]

  Copyright   [This file is part of Bdd Scout package.
               Copyright (C) 2008, 2017 UM-FERI
               UM-FERI, Smetanova ulica 17, SI-2000 Maribor, Slovenia

               Bdd Scout is free software; you can redistribute it and/or modify
               it under the terms of the GNU General Public License as
               published by the Free Software Foundation; either version 2
               of the License, or (at your option) any later version.

               Bdd Scout is distributed in the hope that it will be useful,
               but WITHOUT ANY WARRANTY; without even the implied warranty of
               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
               GNU General Public License for more details.

               You should have received a copy of the GNU General Public
               License along with this program; if not, write to the Free
               Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
               Boston, MA 02110-1301 USA.]
  ************************************************************************/

typedef struct BddscoutStubs {
    int magic;
    const struct BddscoutStubHooks *hooks;

    void (*biddy_InitMNG) (Biddy_Manager *mng, int gddtype); /* 1 */
    void (*biddy_ExitMNG) (Biddy_Manager *mng); /* 2 */
    Biddy_String (*biddy_About) (); /* 3 */
    int (*biddy_Managed_GetManagerType) (Biddy_Manager MNG); /* 4 */
    void (*biddy_Managed_SetManagerParameters) (Biddy_Manager MNG, float gcr, float gcrF, float gcrX, float rr, float rrF, float rrX, float st, float fst, float cst, float fcst); /* 5 */
    Biddy_Edge (*biddy_GetThen) (Biddy_Edge f); /* 6 */
    Biddy_Edge (*biddy_GetElse) (Biddy_Edge f); /* 7 */
    Biddy_Variable (*biddy_GetTopVariable) (Biddy_Edge f); /* 8 */
    Biddy_Boolean (*biddy_Managed_IsEqv) (Biddy_Manager MNG1, Biddy_Edge f1, Biddy_Manager MNG2, Biddy_Edge f2); /* 9 */
    void (*biddy_Managed_SelectNode) (Biddy_Manager MNG, Biddy_Edge f); /* 10 */
    void (*biddy_Managed_DeselectNode) (Biddy_Manager MNG, Biddy_Edge f); /* 11 */
    Biddy_Boolean (*biddy_Managed_IsSelected) (Biddy_Manager MNG, Biddy_Edge f); /* 12 */
    void (*biddy_Managed_SelectFunction) (Biddy_Manager MNG, Biddy_Edge f); /* 13 */
    void (*biddy_Managed_DeselectAll) (Biddy_Manager MNG); /* 14 */
    Biddy_Edge (*biddy_Managed_GetTerminal) (Biddy_Manager MNG); /* 15 */
    Biddy_Edge (*biddy_Managed_GetConstantZero) (Biddy_Manager MNG); /* 16 */
    Biddy_Edge (*biddy_Managed_GetConstantOne) (Biddy_Manager MNG); /* 17 */
    Biddy_Edge (*biddy_Managed_GetBaseSet) (Biddy_Manager MNG); /* 18 */
    Biddy_Variable (*biddy_Managed_GetVariable) (Biddy_Manager MNG, Biddy_String x); /* 19 */
    Biddy_Variable (*biddy_Managed_GetPrevVariable) (Biddy_Manager MNG, Biddy_Variable v); /* 20 */
    Biddy_Variable (*biddy_Managed_GetNextVariable) (Biddy_Manager MNG, Biddy_Variable v); /* 21 */
    Biddy_Edge (*biddy_Managed_GetVariableEdge) (Biddy_Manager MNG, Biddy_Variable v); /* 22 */
    Biddy_Edge (*biddy_Managed_GetElementEdge) (Biddy_Manager MNG, Biddy_Variable v); /* 23 */
    Biddy_String (*biddy_Managed_GetVariableName) (Biddy_Manager MNG, Biddy_Variable v); /* 24 */
    Biddy_Edge (*biddy_Managed_GetTopVariableEdge) (Biddy_Manager MNG, Biddy_Edge f); /* 25 */
    Biddy_String (*biddy_Managed_GetTopVariableName) (Biddy_Manager MNG, Biddy_Edge f); /* 26 */
    char (*biddy_Managed_GetTopVariableChar) (Biddy_Manager MNG, Biddy_Edge f); /* 27 */
    void (*biddy_Managed_ResetVariablesValue) (Biddy_Manager MNG); /* 28 */
    void (*biddy_Managed_SetVariableValue) (Biddy_Manager MNG, Biddy_Variable v, Biddy_Edge f); /* 29 */
    Biddy_Boolean (*biddy_Managed_IsSmaller) (Biddy_Manager MNG, Biddy_Variable fv, Biddy_Variable gv); /* 30 */
    Biddy_Variable (*biddy_Managed_FoaVariable) (Biddy_Manager MNG, Biddy_String x, Biddy_Boolean varelem); /* 31 */
    Biddy_Edge (*biddy_Managed_AddVariableByName) (Biddy_Manager MNG, Biddy_String x); /* 32 */
    Biddy_Edge (*biddy_Managed_AddElementByName) (Biddy_Manager MNG, Biddy_String x); /* 33 */
    Biddy_Edge (*biddy_Managed_AddVariableBelow) (Biddy_Manager MNG, Biddy_Variable v); /* 34 */
    Biddy_Edge (*biddy_Managed_AddVariableAbove) (Biddy_Manager MNG, Biddy_Variable v); /* 35 */
    Biddy_Edge (*biddy_Managed_TransferMark) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Boolean mark, Biddy_Boolean leftright); /* 36 */
    Biddy_Edge (*biddy_Managed_IncTag) (Biddy_Manager MNG, Biddy_Edge f); /* 37 */
    Biddy_Edge (*biddy_Managed_TaggedFoaNode) (Biddy_Manager MNG, Biddy_Variable v, Biddy_Edge pf, Biddy_Edge pt, Biddy_Variable ptag, Biddy_Boolean garbageAllowed); /* 38 */
    Biddy_Edge (*biddy_Managed_Not) (Biddy_Manager MNG, Biddy_Edge f); /* 39 */
    Biddy_Edge (*biddy_Managed_ITE) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g, Biddy_Edge h); /* 40 */
    Biddy_Edge (*biddy_Managed_And) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 41 */
    Biddy_Edge (*biddy_Managed_Or) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 42 */
    Biddy_Edge (*biddy_Managed_Nand) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 43 */
    Biddy_Edge (*biddy_Managed_Nor) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 44 */
    Biddy_Edge (*biddy_Managed_Xor) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 45 */
    Biddy_Edge (*biddy_Managed_Xnor) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 46 */
    Biddy_Edge (*biddy_Managed_Leq) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 47 */
    Biddy_Edge (*biddy_Managed_Gt) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 48 */
    Biddy_Boolean (*biddy_Managed_IsLeq) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 49 */
    Biddy_Edge (*biddy_Managed_Restrict) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Variable v, Biddy_Boolean value); /* 50 */
    Biddy_Edge (*biddy_Managed_Compose) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g, Biddy_Variable v); /* 51 */
    Biddy_Edge (*biddy_Managed_E) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Variable v); /* 52 */
    Biddy_Edge (*biddy_Managed_A) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Variable v); /* 53 */
    Biddy_Boolean (*biddy_Managed_IsVariableDependent) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Variable v); /* 54 */
    Biddy_Edge (*biddy_Managed_ExistAbstract) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge cube); /* 55 */
    Biddy_Edge (*biddy_Managed_UnivAbstract) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge cube); /* 56 */
    Biddy_Edge (*biddy_Managed_AndAbstract) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g, Biddy_Edge cube); /* 57 */
    Biddy_Edge (*biddy_Managed_Constrain) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge c); /* 58 */
    Biddy_Edge (*biddy_Managed_Simplify) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge c); /* 59 */
    Biddy_Edge (*biddy_Managed_Support) (Biddy_Manager MNG, Biddy_Edge f); /* 60 */
    Biddy_Edge (*biddy_Managed_Replace) (Biddy_Manager MNG, Biddy_Edge f); /* 61 */
    Biddy_Edge (*biddy_Managed_Change) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Variable v); /* 62 */
    Biddy_Edge (*biddy_Managed_Subset) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Variable v, Biddy_Boolean value); /* 63 */
    Biddy_Boolean (*biddy_Managed_IsOK) (Biddy_Manager MNG, Biddy_Edge f); /* 64 */
    void (*biddy_Managed_GC) (Biddy_Manager MNG, Biddy_Variable target, Biddy_Boolean purge, Biddy_Boolean total); /* 65 */
    void (*biddy_Managed_Clean) (Biddy_Manager MNG); /* 66 */
    void (*biddy_Managed_Purge) (Biddy_Manager MNG); /* 67 */
    void (*biddy_Managed_PurgeAndReorder) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Boolean converge); /* 68 */
    void (*biddy_Managed_Refresh) (Biddy_Manager MNG, Biddy_Edge f); /* 69 */
    void (*biddy_Managed_AddCache) (Biddy_Manager MNG, Biddy_GCFunction gc); /* 70 */
    unsigned int (*biddy_Managed_AddFormula) (Biddy_Manager MNG, Biddy_String x, Biddy_Edge f, int count); /* 71 */
    Biddy_Boolean (*biddy_Managed_FindFormula) (Biddy_Manager MNG, Biddy_String x, Biddy_Edge *f); /* 72 */
    Biddy_Boolean (*biddy_Managed_DeleteFormula) (Biddy_Manager MNG, Biddy_String x); /* 73 */
    Biddy_Boolean (*biddy_Managed_DeleteIthFormula) (Biddy_Manager MNG, unsigned int i); /* 74 */
    Biddy_Edge (*biddy_Managed_GetIthFormula) (Biddy_Manager MNG, unsigned int i); /* 75 */
    Biddy_String (*biddy_Managed_GetIthFormulaName) (Biddy_Manager MNG, unsigned int i); /* 76 */
    Biddy_Variable (*biddy_Managed_SwapWithHigher) (Biddy_Manager MNG, Biddy_Variable v); /* 77 */
    Biddy_Variable (*biddy_Managed_SwapWithLower) (Biddy_Manager MNG, Biddy_Variable v); /* 78 */
    Biddy_Boolean (*biddy_Managed_Sifting) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Boolean converge); /* 79 */
    Biddy_Edge (*biddy_Managed_Copy) (Biddy_Manager MNG1, Biddy_Manager MNG2, Biddy_Edge f); /* 80 */
    void (*biddy_Managed_CopyFormula) (Biddy_Manager MNG1, Biddy_Manager MNG2, Biddy_String x); /* 81 */
    Biddy_Boolean (*biddy_Managed_Eval) (Biddy_Manager MNG, Biddy_Edge f); /* 82 */
    Biddy_Edge (*biddy_Managed_Random) (Biddy_Manager MNG, Biddy_Edge support, double r); /* 83 */
    Biddy_Edge (*biddy_Managed_RandomSet) (Biddy_Manager MNG, Biddy_Edge empty, double r); /* 84 */

    unsigned int (*biddy_Managed_NodeNumber) (Biddy_Manager MNG, Biddy_Edge f); /* 85 */
    unsigned int (*biddy_NodeMaxLevel) (Biddy_Edge f); /* 86 */
    float (*biddy_NodeAvgLevel) (Biddy_Edge f); /* 87 */
    Biddy_Variable (*biddy_Managed_VariableTableNum) (Biddy_Manager MNG); /* 88 */
    unsigned int (*biddy_Managed_NodeTableSize) (Biddy_Manager MNG); /* 89 */
    unsigned int (*biddy_Managed_NodeTableBlockNumber) (Biddy_Manager MNG); /* 90 */
    unsigned int (*biddy_Managed_NodeTableGenerated) (Biddy_Manager MNG); /* 91 */
    unsigned int (*biddy_Managed_NodeTableMax) (Biddy_Manager MNG); /* 92 */
    unsigned int (*biddy_Managed_NodeTableNum) (Biddy_Manager MNG); /* 93 */
    unsigned int (*biddy_Managed_NodeTableNumVar) (Biddy_Manager MNG, Biddy_Variable v); /* 94 */
    unsigned int (*biddy_Managed_NodeTableGCNumber) (Biddy_Manager MNG); /* 95 */
    unsigned int (*biddy_Managed_NodeTableSwapNumber) (Biddy_Manager MNG); /* 96 */
    unsigned int (*biddy_Managed_NodeTableSiftingNumber) (Biddy_Manager MNG); /* 97 */
    unsigned int (*biddy_Managed_NodeTableResizeNumber) (Biddy_Manager MNG); /* 98 */
    unsigned int (*biddy_Managed_NodeTableITENumber) (Biddy_Manager MNG); /* 99 */
    unsigned long long int (*biddy_Managed_NodeTableITERecursiveNumber) (Biddy_Manager MNG); /* 100 */
    unsigned int (*biddy_Managed_NodeTableANDORNumber) (Biddy_Manager MNG); /* 101 */
    unsigned long long int (*biddy_Managed_NodeTableANDORRecursiveNumber) (Biddy_Manager MNG); /* 102 */
    unsigned int (*biddy_Managed_NodeTableXORNumber) (Biddy_Manager MNG); /* 103 */
    unsigned long long int (*biddy_Managed_NodeTableXORRecursiveNumber) (Biddy_Manager MNG); /* 104 */
    clock_t (*biddy_Managed_NodeTableGCTime) (Biddy_Manager MNG); /* 105 */
    unsigned long long int (*biddy_Managed_NodeTableGCObsoleteNumber) (Biddy_Manager MNG); /* 106 */
    clock_t (*biddy_Managed_NodeTableDRTime) (Biddy_Manager MNG); /* 107 */
    unsigned int (*biddy_Managed_FormulaTableNum) (Biddy_Manager MNG); /* 108 */
    unsigned int (*biddy_Managed_ListUsed) (Biddy_Manager MNG); /* 109 */
    unsigned int (*biddy_Managed_ListMaxLength) (Biddy_Manager MNG); /* 110 */
    float (*biddy_Managed_ListAvgLength) (Biddy_Manager MNG); /* 111 */
    unsigned long long int (*biddy_Managed_OPCacheSearch) (Biddy_Manager MNG); /* 112 */
    unsigned long long int (*biddy_Managed_OPCacheFind) (Biddy_Manager MNG); /* 113 */
    unsigned long long int (*biddy_Managed_OPCacheOverwrite) (Biddy_Manager MNG); /* 114 */
    unsigned int (*biddy_Managed_NodeNumberPlain) (Biddy_Manager MNG, Biddy_Edge f); /* 115 */
    unsigned int (*biddy_Managed_DependentVariableNumber) (Biddy_Manager MNG, Biddy_Edge f); /* 116 */
    void (*biddy_Managed_NodeVarNumber) (Biddy_Manager MNG, Biddy_Edge f, unsigned int *n, unsigned int *v); /* 117 */
    unsigned long long int (*biddy_Managed_CountPaths) (Biddy_Manager MNG, Biddy_Edge f); /* 118 */
    double (*biddy_Managed_CountMinterm) (Biddy_Manager MNG, Biddy_Edge f, unsigned int nvars); /* 119 */
    double (*biddy_Managed_DensityFunction) (Biddy_Manager MNG, Biddy_Edge f, unsigned int nvars); /* 120 */
    double (*biddy_Managed_DensityBDD) (Biddy_Manager MNG, Biddy_Edge f, unsigned int nvars); /* 121 */
    unsigned long long int (*biddy_Managed_ReadMemoryInUse) (Biddy_Manager MNG); /* 122 */
    void (*biddy_Managed_PrintInfo) (Biddy_Manager MNG, FILE *f); /* 123 */

    Biddy_String (*biddy_Managed_Eval0) (Biddy_Manager MNG, Biddy_String s); /* 124 */
    Biddy_Edge (*biddy_Managed_Eval1x) (Biddy_Manager MNG, Biddy_String s, Biddy_LookupFunction lf); /* 125 */
    Biddy_Edge (*biddy_Managed_Eval2) (Biddy_Manager MNG, Biddy_String boolFunc); /* 126 */
    void (*biddy_Managed_ReadVerilogFile) (Biddy_Manager MNG, const char filename[], Biddy_String prefix); /* 127 */
    void (*biddy_Managed_PrintfBDD) (Biddy_Manager MNG, Biddy_Edge f); /* 128 */
    void (*biddy_Managed_WriteBDD) (Biddy_Manager MNG, const char filename[], Biddy_Edge f, Biddy_String label); /* 129 */
    void (*biddy_Managed_PrintfTable) (Biddy_Manager MNG, Biddy_Edge f); /* 130 */
    void (*biddy_Managed_WriteTable) (Biddy_Manager MNG, const char filename[], Biddy_Edge f); /* 131 */
    void (*biddy_Managed_PrintfSOP) (Biddy_Manager MNG, Biddy_Edge f); /* 132 */
    void (*biddy_Managed_WriteSOP) (Biddy_Manager MNG, const char filename[], Biddy_Edge f); /* 133 */
    unsigned int (*biddy_Managed_WriteDot) (Biddy_Manager MNG, const char filename[], Biddy_Edge f, const char label[], int id, Biddy_Boolean cudd); /* 134 */
    unsigned int (*biddy_Managed_WriteBddview) (Biddy_Manager MNG, const char filename[], Biddy_Edge f, const char label[], Biddy_XY *table); /* 135 */

    Biddy_Manager (*bddscout_GetActiveManager) (); /* 1 */

} BddscoutStubs;

#ifdef __cplusplus
extern "C" {
#endif
extern const BddscoutStubs *bddscoutStubsPtr;
#ifdef __cplusplus
}
#endif

#if defined(USE_BDDSCOUT_STUBS)

#define Biddy_InitMNG \
	(bddscoutStubsPtr->biddy_InitMNG) /* 1 */
#define Biddy_ExitMNG \
	(bddscoutStubsPtr->biddy_ExitMNG) /* 2 */
#define Biddy_About \
	(bddscoutStubsPtr->biddy_About) /* 3 */
#define Biddy_Managed_GetManagerType \
	(bddscoutStubsPtr->biddy_Managed_GetManagerType) /* 4 */
#define Biddy_Managed_SetManagerParameters \
	(bddscoutStubsPtr->biddy_Managed_SetManagerParameters) /* 5 */
#define Biddy_GetThen \
	(bddscoutStubsPtr->biddy_GetThen) /* 6 */
#define Biddy_GetElse \
	(bddscoutStubsPtr->biddy_GetElse) /* 7 */
#define Biddy_GetTopVariable \
	(bddscoutStubsPtr->biddy_GetTopVariable) /* 8 */
#define Biddy_Managed_IsEqv \
	(bddscoutStubsPtr->biddy_Managed_IsEqv) /* 9 */
#define Biddy_Managed_SelectNode \
	(bddscoutStubsPtr->biddy_Managed_SelectNode) /* 10 */
#define Biddy_Managed_DeselectNode \
	(bddscoutStubsPtr->biddy_Managed_DeselectNode) /* 11 */
#define Biddy_Managed_IsSelected \
	(bddscoutStubsPtr->biddy_Managed_IsSelected) /* 12 */
#define Biddy_Managed_SelectFunction \
	(bddscoutStubsPtr->biddy_Managed_SelectFunction) /* 13 */
#define Biddy_Managed_DeselectAll \
	(bddscoutStubsPtr->biddy_Managed_DeselectAll) /* 14 */
#define Biddy_Managed_GetTerminal \
	(bddscoutStubsPtr->biddy_Managed_GetTerminal) /* 15 */
#define Biddy_Managed_GetConstantZero \
	(bddscoutStubsPtr->biddy_Managed_GetConstantZero) /* 16 */
#define Biddy_Managed_GetConstantOne \
	(bddscoutStubsPtr->biddy_Managed_GetConstantOne) /* 17 */
#define Biddy_Managed_GetBaseSet \
	(bddscoutStubsPtr->biddy_Managed_GetBaseSet) /* 18 */
#define Biddy_Managed_GetVariable \
	(bddscoutStubsPtr->biddy_Managed_GetVariable) /* 19 */
#define Biddy_Managed_GetPrevVariable \
	(bddscoutStubsPtr->biddy_Managed_GetPrevVariable) /* 20 */
#define Biddy_Managed_GetNextVariable \
	(bddscoutStubsPtr->biddy_Managed_GetNextVariable) /* 21 */
#define Biddy_Managed_GetVariableEdge \
	(bddscoutStubsPtr->biddy_Managed_GetVariableEdge) /* 22 */
#define Biddy_Managed_GetElementEdge \
	(bddscoutStubsPtr->biddy_Managed_GetElementEdge) /* 23 */
#define Biddy_Managed_GetVariableName \
	(bddscoutStubsPtr->biddy_Managed_GetVariableName) /* 24 */
#define Biddy_Managed_GetTopVariableEdge \
	(bddscoutStubsPtr->biddy_Managed_GetTopVariableEdge) /* 25 */
#define Biddy_Managed_GetTopVariableName \
	(bddscoutStubsPtr->biddy_Managed_GetTopVariableName) /* 26 */
#define Biddy_Managed_GetTopVariableChar \
	(bddscoutStubsPtr->biddy_Managed_GetTopVariableChar) /* 27 */
#define Biddy_Managed_ResetVariablesValue \
	(bddscoutStubsPtr->biddy_Managed_ResetVariablesValue) /* 28 */
#define Biddy_Managed_SetVariableValue \
	(bddscoutStubsPtr->biddy_Managed_SetVariableValue) /* 29 */
#define Biddy_Managed_IsSmaller \
	(bddscoutStubsPtr->biddy_Managed_IsSmaller) /* 30 */
#define Biddy_Managed_FoaVariable \
	(bddscoutStubsPtr->biddy_Managed_FoaVariable) /* 31 */
#define Biddy_Managed_AddVariableByName \
	(bddscoutStubsPtr->biddy_Managed_AddVariableByName) /* 32 */
#define Biddy_Managed_AddElementByName \
	(bddscoutStubsPtr->biddy_Managed_AddElementByName) /* 33 */
#define Biddy_Managed_AddVariableBelow \
	(bddscoutStubsPtr->biddy_Managed_AddVariableBelow) /* 34 */
#define Biddy_Managed_AddVariableAbove \
	(bddscoutStubsPtr->biddy_Managed_AddVariableAbove) /* 35 */
#define Biddy_Managed_TransferMark \
	(bddscoutStubsPtr->biddy_Managed_TransferMark) /* 36 */
#define Biddy_Managed_IncTag \
	(bddscoutStubsPtr->biddy_Managed_IncTag) /* 37 */
#define Biddy_Managed_TaggedFoaNode \
	(bddscoutStubsPtr->biddy_Managed_TaggedFoaNode) /* 38 */
#define Biddy_Managed_Not \
	(bddscoutStubsPtr->biddy_Managed_Not) /* 39 */
#define Biddy_Managed_ITE \
	(bddscoutStubsPtr->biddy_Managed_ITE) /* 40 */
#define Biddy_Managed_And \
	(bddscoutStubsPtr->biddy_Managed_And) /* 41 */
#define Biddy_Managed_Or \
	(bddscoutStubsPtr->biddy_Managed_Or) /* 42 */
#define Biddy_Managed_Nand \
	(bddscoutStubsPtr->biddy_Managed_Nand) /* 43 */
#define Biddy_Managed_Nor \
	(bddscoutStubsPtr->biddy_Managed_Nor) /* 44 */
#define Biddy_Managed_Xor \
	(bddscoutStubsPtr->biddy_Managed_Xor) /* 45 */
#define Biddy_Managed_Xnor \
	(bddscoutStubsPtr->biddy_Managed_Xnor) /* 46 */
#define Biddy_Managed_Leq \
	(bddscoutStubsPtr->biddy_Managed_Leq) /* 47 */
#define Biddy_Managed_Gt \
	(bddscoutStubsPtr->biddy_Managed_Gt) /* 48 */
#define Biddy_Managed_IsLeq \
	(bddscoutStubsPtr->biddy_Managed_IsLeq) /* 49 */
#define Biddy_Managed_Restrict \
	(bddscoutStubsPtr->biddy_Managed_Restrict) /* 50 */
#define Biddy_Managed_Compose \
	(bddscoutStubsPtr->biddy_Managed_Compose) /* 51 */
#define Biddy_Managed_E \
	(bddscoutStubsPtr->biddy_Managed_E) /* 52 */
#define Biddy_Managed_A \
	(bddscoutStubsPtr->biddy_Managed_A) /* 53 */
#define Biddy_Managed_IsVariableDependent \
	(bddscoutStubsPtr->biddy_Managed_IsVariableDependent) /* 54 */
#define Biddy_Managed_ExistAbstract \
	(bddscoutStubsPtr->biddy_Managed_ExistAbstract) /* 55 */
#define Biddy_Managed_UnivAbstract \
	(bddscoutStubsPtr->biddy_Managed_UnivAbstract) /* 56 */
#define Biddy_Managed_AndAbstract \
	(bddscoutStubsPtr->biddy_Managed_AndAbstract) /* 57 */
#define Biddy_Managed_Constrain \
	(bddscoutStubsPtr->biddy_Managed_Constrain) /* 58 */
#define Biddy_Managed_Simplify \
	(bddscoutStubsPtr->biddy_Managed_Simplify) /* 59 */
#define Biddy_Managed_Support \
	(bddscoutStubsPtr->biddy_Managed_Support) /* 60 */
#define Biddy_Managed_Replace \
	(bddscoutStubsPtr->biddy_Managed_Replace) /* 61 */
#define Biddy_Managed_Change \
	(bddscoutStubsPtr->biddy_Managed_Change) /* 62 */
#define Biddy_Managed_Subset \
	(bddscoutStubsPtr->biddy_Managed_Subset) /* 63 */
#define Biddy_Managed_IsOK \
	(bddscoutStubsPtr->biddy_Managed_IsOK) /* 64 */
#define Biddy_Managed_GC \
	(bddscoutStubsPtr->biddy_Managed_GC) /* 65 */
#define Biddy_Managed_Clean \
	(bddscoutStubsPtr->biddy_Managed_Clean) /* 66 */
#define Biddy_Managed_Purge \
	(bddscoutStubsPtr->biddy_Managed_Purge) /* 67 */
#define Biddy_Managed_PurgeAndReorder \
	(bddscoutStubsPtr->biddy_Managed_PurgeAndReorder) /* 68 */
#define Biddy_Managed_Refresh \
	(bddscoutStubsPtr->biddy_Managed_Refresh) /* 69 */
#define Biddy_Managed_AddCache \
	(bddscoutStubsPtr->biddy_Managed_AddCache) /* 70 */
#define Biddy_Managed_AddFormula \
	(bddscoutStubsPtr->biddy_Managed_AddFormula) /* 71 */
#define Biddy_Managed_FindFormula \
	(bddscoutStubsPtr->biddy_Managed_FindFormula) /* 72 */
#define Biddy_Managed_DeleteFormula \
	(bddscoutStubsPtr->biddy_Managed_DeleteFormula) /* 73 */
#define Biddy_Managed_DeleteIthFormula \
	(bddscoutStubsPtr->biddy_Managed_DeleteIthFormula) /* 74 */
#define Biddy_Managed_GetIthFormula \
	(bddscoutStubsPtr->biddy_Managed_GetIthFormula) /* 75 */
#define Biddy_Managed_GetIthFormulaName \
	(bddscoutStubsPtr->biddy_Managed_GetIthFormulaName) /* 76 */
#define Biddy_Managed_SwapWithHigher \
	(bddscoutStubsPtr->biddy_Managed_SwapWithHigher) /* 77 */
#define Biddy_Managed_SwapWithLower \
	(bddscoutStubsPtr->biddy_Managed_SwapWithLower) /* 78 */
#define Biddy_Managed_Sifting \
	(bddscoutStubsPtr->biddy_Managed_Sifting) /* 79 */
#define Biddy_Managed_Copy \
	(bddscoutStubsPtr->biddy_Managed_Copy) /* 80 */
#define Biddy_Managed_CopyFormula \
	(bddscoutStubsPtr->biddy_Managed_CopyFormula) /* 81 */
#define Biddy_Managed_Eval \
	(bddscoutStubsPtr->biddy_Managed_Eval) /* 82 */
#define Biddy_Managed_Random \
	(bddscoutStubsPtr->biddy_Managed_Random) /* 83 */
#define Biddy_Managed_RandomSet \
	(bddscoutStubsPtr->biddy_Managed_RandomSet) /* 84 */

#define Biddy_Managed_NodeNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeNumber) /* 85 */
#define Biddy_NodeMaxLevel \
	(bddscoutStubsPtr->biddy_NodeMaxLevel) /* 86 */
#define Biddy_NodeAvgLevel \
	(bddscoutStubsPtr->biddy_NodeAvgLevel) /* 87 */
#define Biddy_Managed_VariableTableNum \
	(bddscoutStubsPtr->biddy_Managed_VariableTableNum) /* 88 */
#define Biddy_Managed_NodeTableSize \
	(bddscoutStubsPtr->biddy_Managed_NodeTableSize) /* 89 */
#define Biddy_Managed_NodeTableBlockNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableBlockNumber) /* 90 */
#define Biddy_Managed_NodeTableGenerated \
	(bddscoutStubsPtr->biddy_Managed_NodeTableGenerated) /* 91 */
#define Biddy_Managed_NodeTableMax \
	(bddscoutStubsPtr->biddy_Managed_NodeTableMax) /* 92 */
#define Biddy_Managed_NodeTableNum \
	(bddscoutStubsPtr->biddy_Managed_NodeTableNum) /* 93 */
#define Biddy_Managed_NodeTableNumVar \
	(bddscoutStubsPtr->biddy_Managed_NodeTableNumVar) /* 94 */
#define Biddy_Managed_NodeTableGCNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableGCNumber) /* 95 */
#define Biddy_Managed_NodeTableSwapNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableSwapNumber) /* 96 */
#define Biddy_Managed_NodeTableSiftingNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableSiftingNumber) /* 97 */
#define Biddy_Managed_NodeTableResizeNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableResizeNumber) /* 98 */
#define Biddy_Managed_NodeTableITENumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableITENumber) /* 99 */
#define Biddy_Managed_NodeTableITERecursiveNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableITERecursiveNumber) /* 100 */
#define Biddy_Managed_NodeTableANDORNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableANDORNumber) /* 101 */
#define Biddy_Managed_NodeTableANDORRecursiveNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableANDORRecursiveNumber) /* 102 */
#define Biddy_Managed_NodeTableXORNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableXORNumber) /* 103 */
#define Biddy_Managed_NodeTableXORRecursiveNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableXORRecursiveNumber) /* 104 */
#define Biddy_Managed_NodeTableGCTime \
	(bddscoutStubsPtr->biddy_Managed_NodeTableGCTime) /* 105 */
#define Biddy_Managed_NodeTableGCObsoleteNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableGCObsoleteNumber) /* 106 */
#define Biddy_Managed_NodeTableDRTime \
	(bddscoutStubsPtr->biddy_Managed_NodeTableDRTime) /* 107 */
#define Biddy_Managed_FormulaTableNum \
	(bddscoutStubsPtr->biddy_Managed_FormulaTableNum) /* 108 */
#define Biddy_Managed_ListUsed \
	(bddscoutStubsPtr->biddy_Managed_ListUsed) /* 109 */
#define Biddy_Managed_ListMaxLength \
	(bddscoutStubsPtr->biddy_Managed_ListMaxLength) /* 110 */
#define Biddy_Managed_ListAvgLength \
	(bddscoutStubsPtr->biddy_Managed_ListAvgLength) /* 111 */
#define Biddy_Managed_OPCacheSearch \
	(bddscoutStubsPtr->biddy_Managed_OPCacheSearch) /* 112 */
#define Biddy_Managed_OPCacheFind \
	(bddscoutStubsPtr->biddy_Managed_OPCacheFind) /* 113 */
#define Biddy_Managed_OPCacheOverwrite \
	(bddscoutStubsPtr->biddy_Managed_OPCacheOverwrite) /* 114 */
#define Biddy_Managed_NodeNumberPlain \
	(bddscoutStubsPtr->biddy_Managed_NodeNumberPlain) /* 115 */
#define Biddy_Managed_DependentVariableNumber \
	(bddscoutStubsPtr->biddy_Managed_DependentVariableNumber) /* 116 */
#define Biddy_Managed_NodeVarNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeVarNumber) /* 117 */
#define Biddy_Managed_CountPaths \
	(bddscoutStubsPtr->biddy_Managed_CountPaths) /* 118 */
#define Biddy_Managed_CountMinterm \
	(bddscoutStubsPtr->biddy_Managed_CountMinterm) /* 119 */
#define Biddy_Managed_DensityFunction \
	(bddscoutStubsPtr->biddy_Managed_DensityFunction) /* 120 */
#define Biddy_Managed_DensityBDD \
	(bddscoutStubsPtr->biddy_Managed_DensityBDD) /* 121 */
#define Biddy_Managed_ReadMemoryInUse \
	(bddscoutStubsPtr->biddy_Managed_ReadMemoryInUse) /* 122 */
#define Biddy_Managed_PrintInfo \
	(bddscoutStubsPtr->biddy_Managed_PrintInfo) /* 123 */

#define Biddy_Managed_Eval0 \
	(bddscoutStubsPtr->biddy_Managed_Eval0) /* 124 */
#define Biddy_Managed_Eval1x \
	(bddscoutStubsPtr->biddy_Managed_Eval1x) /* 125 */
#define Biddy_Managed_Eval2 \
	(bddscoutStubsPtr->biddy_Managed_Eval2) /* 126 */
#define Biddy_Managed_ReadVerilogFile\
	(bddscoutStubsPtr->biddy_Managed_ReadVerilogFile) /* 127 */
#define Biddy_Managed_PrintfBDD\
	(bddscoutStubsPtr->biddy_Managed_PrintfBDD) /* 128 */
#define Biddy_Managed_WriteBDD \
	(bddscoutStubsPtr->biddy_Managed_WriteBDD) /* 129 */
#define Biddy_Managed_PrintfTable \
	(bddscoutStubsPtr->biddy_Managed_PrintfTable) /* 130 */
#define Biddy_Managed_WriteTable \
	(bddscoutStubsPtr->biddy_Managed_WriteTable) /* 131 */
#define Biddy_Managed_PrintfSOP \
	(bddscoutStubsPtr->biddy_Managed_PrintfSOP) /* 132 */
#define Biddy_Managed_WriteSOP \
	(bddscoutStubsPtr->biddy_Managed_WriteSOP) /* 133 */
#define Biddy_Managed_WriteDot \
	(bddscoutStubsPtr->biddy_Managed_WriteDot) /* 134 */
#define Biddy_Managed_WriteBddview \
	(bddscoutStubsPtr->biddy_Managed_WriteBddview) /* 135 */

#define Bddscout_GetActiveManager \
	(bddscoutStubsPtr->bddscout_GetActiveManager) /* 1 */

#endif /* defined(USE_BDDSCOUT_STUBS) */
