/**CFile*******************************************************************
  PackageName [Bdd Scout]
  Synopsis    [Bdd Scout]

  FileName    [bddscoutStubInit.c]
  Revision    [$Revision: 102 $]
  Date        [$Date: 2015-10-07 11:51:45 +0200 (sre, 07 okt 2015) $]
  Authors     [Robert Meolic (robert.meolic@um.si)]
  Description [Generated by genStubs.tcl, see http://wiki.tcl.tk/3358]
  SeeAlso     [bddscout.h, bddscout.decls, bddscoutDecls.h, bddscoutStubLib.c]

  Copyright   [This file is part of Bdd Scout package.
               Copyright (C) 2008, 2015 UM-FERI
               UM-FERI, Smetanova ulica 17, SI-2000 Maribor, Slovenia

               Bdd Scout is free software; you can redistribute it and/or modify
               it under the terms of the GNU General Public License as
               published by the Free Software Foundation; either version 2
               of the License, or (at your option) any later version.

               Bdd Scout is distributed in the hope that it will be useful,
               but WITHOUT ANY WARRANTY; without even the implied warranty of
               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
               GNU General Public License for more details.

               You should have received a copy of the GNU General Public
               License along with this program; if not, write to the Free
               Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
               Boston, MA 02110-1301 USA.]
  ************************************************************************/

#include "bddscout.h"

BddscoutStubs bddscoutStubs = {
    TCL_STUB_MAGIC,
    0,
    Biddy_Init, /* 1 */
    Biddy_Exit, /* 2 */
    Biddy_About, /* 3 */
    Biddy_GetThen, /* 4 */
    Biddy_GetElse, /* 5 */
    Biddy_GetTopVariable, /* 6 */
    Biddy_SelectNode, /* 7 */
    Biddy_DeselectNode, /* 8 */
    Biddy_IsSelected, /* 9 */
    Biddy_NodeSelect, /* 10 */
    Biddy_NodeRepair, /* 11 */
    Biddy_NOT, /* 12 */
    Biddy_TransferMark, /* 13 */
    Biddy_Managed_GetConstantZero, /* 14 */
    Biddy_Managed_GetConstantOne, /* 15 */
    Biddy_Managed_GetVariableName, /* 16 */
    Biddy_Managed_GetTopVariableName, /* 17 */
    Biddy_Managed_GetTopVariableChar, /* 18 */
    Biddy_Managed_ResetVariablesValue, /* 19 */
    Biddy_Managed_SetVariableValue, /* 20 */
    Biddy_Managed_IsSmaller, /* 21 */
    Biddy_Managed_AddVariable, /* 22 */
    Biddy_Managed_AddVariableBelow, /* 23 */
    Biddy_Managed_AddVariableAbove, /* 24 */
    Biddy_Managed_FoaVariable, /* 25 */
    Biddy_Managed_FoaNode, /* 26 */
    Biddy_Managed_ITE, /* 27 */
    Biddy_Managed_And, /* 28 */
    Biddy_Managed_Or, /* 29 */
    Biddy_Managed_Nand, /* 30 */
    Biddy_Managed_Nor, /* 31 */
    Biddy_Managed_Xor, /* 32 */
    Biddy_Managed_Xnor, /* 33 */
    Biddy_Managed_Leq, /* 34 */
    Biddy_Managed_Intersect, /* 35 */
    Biddy_Managed_Restrict, /* 36 */
    Biddy_Managed_Compose, /* 37 */
    Biddy_Managed_E, /* 38 */
    Biddy_Managed_A, /* 39 */
    Biddy_Managed_IsVariableDependent, /* 40 */
    Biddy_Managed_ExistAbstract, /* 41 */
    Biddy_Managed_UnivAbstract, /* 42 */
    Biddy_Managed_AndAbstract, /* 43 */
    Biddy_Managed_Constrain, /* 44 */
    Biddy_Managed_Simplify, /* 45 */
    Biddy_Managed_Support, /* 46 */
    Biddy_Managed_Replace, /* 47 */
    Biddy_Managed_IsOK, /* 48 */
    Biddy_Managed_Garbage, /* 49 */
    Biddy_Managed_Clean, /* 50 */
    Biddy_Managed_Purge, /* 51 */
    Biddy_Managed_PurgeAndReorder, /* 52 */
    Biddy_Managed_Refresh, /* 53 */
    Biddy_Managed_ClearAll, /* 54 */
    Biddy_Managed_AddCache, /* 55 */
    Biddy_Managed_AddFormula, /* 56 */
    Biddy_Managed_FindFormula, /* 57 */
    Biddy_Managed_DeleteFormula, /* 58 */
    Biddy_Managed_DeleteIthFormula, /* 59 */
    Biddy_Managed_GetIthFormula, /* 60 */
    Biddy_Managed_GetIthFormulaName, /* 61 */
    Biddy_Managed_SwapWithHigher, /* 62 */
    Biddy_Managed_SwapWithLower, /* 63 */
    Biddy_Managed_Sifting, /* 64 */

    Biddy_NodeNumber, /* 65 */
    Biddy_NodeMaxLevel, /* 66 */
    Biddy_NodeAvgLevel, /* 67 */
    Biddy_Managed_VariableTableNum, /* 68 */
    Biddy_Managed_NodeTableSize, /* 69 */
    Biddy_Managed_NodeTableMax, /* 70 */
    Biddy_Managed_NodeTableNum, /* 71 */
    Biddy_Managed_NodeTableNumVar, /* 72 */
    Biddy_Managed_NodeTableNumF, /* 73 */
    Biddy_Managed_NodeTableFOA, /* 74 */
    Biddy_Managed_NodeTableCompare, /* 75 */
    Biddy_Managed_NodeTableAdd, /* 76 */
    Biddy_Managed_NodeTableGarbage, /* 77 */
    Biddy_Managed_NodeTableGenerated, /* 78 */
    Biddy_Managed_NodeTableBlockNumber, /* 79 */
    Biddy_Managed_NodeTableSwapNumber, /* 80 */
    Biddy_Managed_NodeTableSiftingNumber, /* 81 */
    Biddy_Managed_ListUsed, /* 82 */
    Biddy_Managed_ListMaxLength, /* 83 */
    Biddy_Managed_ListAvgLength, /* 84 */
    Biddy_Managed_IteCacheSearch, /* 85 */
    Biddy_Managed_IteCacheFind, /* 86 */
    Biddy_Managed_IteCacheOverwrite, /* 87 */
    Biddy_Managed_NodeNumberPlain, /* 88 */
    Biddy_Managed_VariableNumber, /* 89 */
    Biddy_Managed_NodeVarNumber, /* 90 */
    Biddy_Managed_CountMinterm, /* 91 */

    Biddy_Managed_Eval0, /* 92 */
    Biddy_Managed_Eval1, /* 93 */
    Biddy_Managed_Eval1x, /* 94 */
    Biddy_Managed_Eval2, /* 95 */
    Biddy_Managed_WriteBDD, /* 96 */
    Biddy_Managed_WriteBDDx, /* 97 */
    Biddy_Managed_WriteDot, /* 98 */
    Biddy_Managed_WriteDotx, /* 99 */
    Biddy_Managed_WriteTable, /* 100 */

};
