/**CFile*******************************************************************
  PackageName [Bdd Scout]
  Synopsis    [Bdd Scout]

  FileName    [bddscoutStubInit.c]
  Revision    [$Revision: 355 $]
  Date        [$Date: 2017-12-12 22:57:11 +0100 (tor, 12 dec 2017) $]
  Authors     [Robert Meolic (robert.meolic@um.si)]
  Description [Generated by genStubs.tcl, see http://wiki.tcl.tk/3358]
  SeeAlso     [bddscout.h, bddscout.decls, bddscoutDecls.h, bddscoutStubLib.c]

  Copyright   [This file is part of Bdd Scout package.
               Copyright (C) 2008, 2017 UM FERI
               UM FERI, Koroska cesta 46, SI-2000 Maribor, Slovenia

               Bdd Scout is free software; you can redistribute it and/or modify
               it under the terms of the GNU General Public License as
               published by the Free Software Foundation; either version 2
               of the License, or (at your option) any later version.

               Bdd Scout is distributed in the hope that it will be useful,
               but WITHOUT ANY WARRANTY; without even the implied warranty of
               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
               GNU General Public License for more details.

               You should have received a copy of the GNU General Public
               License along with this program; if not, write to the Free
               Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
               Boston, MA 02110-1301 USA.]
  ************************************************************************/

#define BUILD_BDDSCOUTSTUBS
#include "bddscoutTcl.h"

BddscoutStubs bddscoutStubs = {
    TCL_STUB_MAGIC,
    0,
    Biddy_InitMNG, /* 1 */
    Biddy_ExitMNG, /* 2 */
    Biddy_About, /* 3 */
    Biddy_Managed_GetManagerType, /* 4 */
    Biddy_Managed_GetManagerName, /* 5 */
    Biddy_Managed_SetManagerParameters, /* 6 */
    Biddy_GetThen, /* 7 */
    Biddy_GetElse, /* 8 */
    Biddy_GetTopVariable, /* 9 */
    Biddy_Managed_IsEqv, /* 10 */
    Biddy_Managed_SelectNode, /* 11 */
    Biddy_Managed_DeselectNode, /* 12 */
    Biddy_Managed_IsSelected, /* 13 */
    Biddy_Managed_SelectFunction, /* 14 */
    Biddy_Managed_DeselectAll, /* 15 */
    Biddy_Managed_GetTerminal, /* 16 */
    Biddy_Managed_GetConstantZero, /* 17 */
    Biddy_Managed_GetConstantOne, /* 18 */
    Biddy_Managed_GetBaseSet, /* 19 */
    Biddy_Managed_GetVariable, /* 20 */
    Biddy_Managed_GetLowestVariable, /* 21 */
    Biddy_Managed_GetIthVariable, /* 22 */
    Biddy_Managed_GetPrevVariable, /* 23 */
    Biddy_Managed_GetNextVariable, /* 24 */
    Biddy_Managed_GetVariableEdge, /* 25 */
    Biddy_Managed_GetElementEdge, /* 26 */
    Biddy_Managed_GetVariableName, /* 27 */
    Biddy_Managed_GetTopVariableEdge, /* 28 */
    Biddy_Managed_GetTopVariableName, /* 29 */
    Biddy_Managed_GetTopVariableChar, /* 30 */
    Biddy_Managed_ResetVariablesValue, /* 31 */
    Biddy_Managed_SetVariableValue, /* 32 */
    Biddy_Managed_GetVariableValue, /* 33 */
    Biddy_Managed_ClearVariablesData, /* 34 */
    Biddy_Managed_SetVariableData, /* 35 */
    Biddy_Managed_GetVariableData, /* 36 */
    Biddy_Managed_IsSmaller, /* 37 */
    Biddy_Managed_IsLowest, /* 38 */
    Biddy_Managed_IsHighest, /* 39 */
    Biddy_Managed_FoaVariable, /* 40 */
    Biddy_Managed_ChangeVariableName, /* 41 */
    Biddy_Managed_AddVariableByName, /* 42 */
    Biddy_Managed_AddElementByName, /* 43 */
    Biddy_Managed_AddVariableBelow, /* 44 */
    Biddy_Managed_AddVariableAbove, /* 45 */
    Biddy_Managed_TransferMark, /* 46 */
    Biddy_Managed_IncTag, /* 47 */
    Biddy_Managed_TaggedFoaNode, /* 48 */
    Biddy_Managed_IsOK, /* 49 */
    Biddy_Managed_GC, /* 50 */
    Biddy_Managed_Clean, /* 51 */
    Biddy_Managed_Purge, /* 52 */
    Biddy_Managed_PurgeAndReorder, /* 53 */
    Biddy_Managed_Refresh, /* 54 */
    Biddy_Managed_AddCache, /* 55 */
    Biddy_Managed_AddFormula, /* 56 */
    Biddy_Managed_FindFormula, /* 57 */
    Biddy_Managed_DeleteFormula, /* 58 */
    Biddy_Managed_DeleteIthFormula, /* 59 */
    Biddy_Managed_GetIthFormula, /* 60 */
    Biddy_Managed_GetIthFormulaName, /* 61 */
    Biddy_Managed_SwapWithHigher, /* 62 */
    Biddy_Managed_SwapWithLower, /* 63 */
    Biddy_Managed_Sifting, /* 64 */
    Biddy_Managed_MinimizeBDD, /* 65 */
    Biddy_Managed_MaximizeBDD, /* 66 */
    Biddy_Managed_Copy, /* 67 */
    Biddy_Managed_CopyFormula, /* 68 */
    Biddy_Managed_Eval, /* 69 */

    Biddy_Managed_Not, /* 70 */
    Biddy_Managed_ITE, /* 71 */
    Biddy_Managed_And, /* 72 */
    Biddy_Managed_Or, /* 73 */
    Biddy_Managed_Nand, /* 74 */
    Biddy_Managed_Nor, /* 75 */
    Biddy_Managed_Xor, /* 76 */
    Biddy_Managed_Xnor, /* 77 */
    Biddy_Managed_Leq, /* 78 */
    Biddy_Managed_Gt, /* 79 */
    Biddy_Managed_IsLeq, /* 80 */
    Biddy_Managed_Restrict, /* 81 */
    Biddy_Managed_Compose, /* 82 */
    Biddy_Managed_E, /* 83 */
    Biddy_Managed_A, /* 84 */
    Biddy_Managed_IsVariableDependent, /* 85 */
    Biddy_Managed_ExistAbstract, /* 86 */
    Biddy_Managed_UnivAbstract, /* 87 */
    Biddy_Managed_AndAbstract, /* 88 */
    Biddy_Managed_Constrain, /* 89 */
    Biddy_Managed_Simplify, /* 90 */
    Biddy_Managed_Support, /* 91 */
    Biddy_Managed_ReplaceByKeyword, /* 92 */
    Biddy_Managed_Change, /* 93 */
    Biddy_Managed_Subset, /* 94 */
    Biddy_Managed_CreateMinterm, /* 95 */
    Biddy_Managed_CreateFunction, /* 96 */
    Biddy_Managed_RandomFunction, /* 97 */
    Biddy_Managed_RandomSet, /* 98 */

    Biddy_Managed_CountNodes, /* 99 */
    Biddy_MaxLevel, /* 100 */
    Biddy_AvgLevel, /* 101 */
    Biddy_Managed_VariableTableNum, /* 102 */
    Biddy_Managed_NodeTableSize, /* 103 */
    Biddy_Managed_NodeTableBlockNumber, /* 104 */
    Biddy_Managed_NodeTableGenerated, /* 105 */
    Biddy_Managed_NodeTableMax, /* 106 */
    Biddy_Managed_NodeTableNum, /* 107 */
    Biddy_Managed_NodeTableNumVar, /* 108 */
    Biddy_Managed_NodeTableResizeNumber, /* 109 */
    Biddy_Managed_NodeTableFoaNumber, /* 110 */
    Biddy_Managed_NodeTableFindNumber, /* 111 */
    Biddy_Managed_NodeTableCompareNumber, /* 112 */
    Biddy_Managed_NodeTableAddNumber, /* 113 */
    Biddy_Managed_NodeTableGCNumber, /* 114 */
    Biddy_Managed_NodeTableGCTime, /* 115 */
    Biddy_Managed_NodeTableGCObsoleteNumber, /* 116 */
    Biddy_Managed_NodeTableSwapNumber, /* 117 */
    Biddy_Managed_NodeTableSiftingNumber, /* 118 */
    Biddy_Managed_NodeTableDRTime, /* 119 */
    Biddy_Managed_NodeTableITENumber, /* 120 */
    Biddy_Managed_NodeTableITERecursiveNumber, /* 121 */
    Biddy_Managed_NodeTableANDORNumber, /* 122 */
    Biddy_Managed_NodeTableANDORRecursiveNumber, /* 123 */
    Biddy_Managed_NodeTableXORNumber, /* 124 */
    Biddy_Managed_NodeTableXORRecursiveNumber, /* 125 */
    Biddy_Managed_FormulaTableNum, /* 126 */
    Biddy_Managed_ListUsed, /* 127 */
    Biddy_Managed_ListMaxLength, /* 128 */
    Biddy_Managed_ListAvgLength, /* 129 */
    Biddy_Managed_OPCacheSearch, /* 130 */
    Biddy_Managed_OPCacheFind, /* 131 */
    Biddy_Managed_OPCacheInsert, /* 132 */
    Biddy_Managed_OPCacheOverwrite, /* 133 */
    Biddy_Managed_CountNodesPlain, /* 134 */
    Biddy_Managed_DependentVariableNumber, /* 135 */
    Biddy_Managed_CountComplementedEdges, /* 136 */
    Biddy_Managed_CountPaths, /* 137 */
    Biddy_Managed_CountMinterms, /* 138 */
    Biddy_Managed_DensityOfFunction, /* 139 */
    Biddy_Managed_DensityOfBDD, /* 140 */
    Biddy_Managed_ReadMemoryInUse, /* 141 */
    Biddy_Managed_PrintInfo, /* 142 */

    Biddy_Managed_Eval0, /* 143 */
    Biddy_Managed_Eval1x, /* 144 */
    Biddy_Managed_Eval2, /* 145 */
    Biddy_Managed_ReadVerilogFile, /* 146 */
    Biddy_Managed_PrintfBDD, /* 147 */
    Biddy_Managed_WriteBDD, /* 148 */
    Biddy_Managed_PrintfTable, /* 149 */
    Biddy_Managed_WriteTable, /* 150 */
    Biddy_Managed_PrintfSOP, /* 151 */
    Biddy_Managed_WriteSOP, /* 152 */
    Biddy_Managed_WriteDot, /* 153 */
    Biddy_Managed_WriteBddview, /* 154 */

    Bddscout_GetActiveManager, /* 1 */
    Bddscout_ClearActiveManager, /* 2 */
    Bddscout_ChangeActiveManager, /* 3 */
};
