/**CFile*******************************************************************
  PackageName [Bdd Scout]
  Synopsis    [Bdd Scout]

  FileName    [bddscoutStubInit.c]
  Revision    [$Revision: 319 $]
  Date        [$Date: 2017-09-30 22:37:26 +0200 (sob, 30 sep 2017) $]
  Authors     [Robert Meolic (robert.meolic@um.si)]
  Description [Generated by genStubs.tcl, see http://wiki.tcl.tk/3358]
  SeeAlso     [bddscout.h, bddscout.decls, bddscoutDecls.h, bddscoutStubLib.c]

  Copyright   [This file is part of Bdd Scout package.
               Copyright (C) 2008, 2017 UM FERI
               UM FERI, Koroska cesta 46, SI-2000 Maribor, Slovenia

               Bdd Scout is free software; you can redistribute it and/or modify
               it under the terms of the GNU General Public License as
               published by the Free Software Foundation; either version 2
               of the License, or (at your option) any later version.

               Bdd Scout is distributed in the hope that it will be useful,
               but WITHOUT ANY WARRANTY; without even the implied warranty of
               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
               GNU General Public License for more details.

               You should have received a copy of the GNU General Public
               License along with this program; if not, write to the Free
               Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
               Boston, MA 02110-1301 USA.]
  ************************************************************************/

#define BUILD_BDDSCOUTSTUBS
#include "bddscoutTcl.h"

BddscoutStubs bddscoutStubs = {
    TCL_STUB_MAGIC,
    0,
    Biddy_InitMNG, /* 1 */
    Biddy_ExitMNG, /* 2 */
    Biddy_About, /* 3 */
    Biddy_Managed_GetManagerType, /* 4 */
    Biddy_Managed_GetManagerName, /* 5 */
    Biddy_Managed_SetManagerParameters, /* 6 */
    Biddy_GetThen, /* 7 */
    Biddy_GetElse, /* 8 */
    Biddy_GetTopVariable, /* 9 */
    Biddy_Managed_IsEqv, /* 10 */
    Biddy_Managed_SelectNode, /* 11 */
    Biddy_Managed_DeselectNode, /* 12 */
    Biddy_Managed_IsSelected, /* 13 */
    Biddy_Managed_SelectFunction, /* 14 */
    Biddy_Managed_DeselectAll, /* 15 */
    Biddy_Managed_GetTerminal, /* 16 */
    Biddy_Managed_GetConstantZero, /* 17 */
    Biddy_Managed_GetConstantOne, /* 18 */
    Biddy_Managed_GetBaseSet, /* 19 */
    Biddy_Managed_GetVariable, /* 20 */
    Biddy_Managed_GetPrevVariable, /* 21 */
    Biddy_Managed_GetNextVariable, /* 22 */
    Biddy_Managed_GetVariableEdge, /* 23 */
    Biddy_Managed_GetElementEdge, /* 24 */
    Biddy_Managed_GetVariableName, /* 25 */
    Biddy_Managed_GetTopVariableEdge, /* 26 */
    Biddy_Managed_GetTopVariableName, /* 27 */
    Biddy_Managed_GetTopVariableChar, /* 28 */
    Biddy_Managed_ResetVariablesValue, /* 29 */
    Biddy_Managed_SetVariableValue, /* 30 */
    Biddy_Managed_IsSmaller, /* 31 */
    Biddy_Managed_FoaVariable, /* 32 */
    Biddy_Managed_ChangeVariableName, /* 33 */
    Biddy_Managed_AddVariableByName, /* 34 */
    Biddy_Managed_AddElementByName, /* 35 */
    Biddy_Managed_AddVariableBelow, /* 36 */
    Biddy_Managed_AddVariableAbove, /* 37 */
    Biddy_Managed_TransferMark, /* 38 */
    Biddy_Managed_IncTag, /* 39 */
    Biddy_Managed_TaggedFoaNode, /* 40 */
    Biddy_Managed_Not, /* 41 */
    Biddy_Managed_ITE, /* 42 */
    Biddy_Managed_And, /* 43 */
    Biddy_Managed_Or, /* 44 */
    Biddy_Managed_Nand, /* 45 */
    Biddy_Managed_Nor, /* 46 */
    Biddy_Managed_Xor, /* 47 */
    Biddy_Managed_Xnor, /* 48 */
    Biddy_Managed_Leq, /* 49 */
    Biddy_Managed_Gt, /* 50 */
    Biddy_Managed_IsLeq, /* 51 */
    Biddy_Managed_Restrict, /* 52 */
    Biddy_Managed_Compose, /* 53 */
    Biddy_Managed_E, /* 54 */
    Biddy_Managed_A, /* 55 */
    Biddy_Managed_IsVariableDependent, /* 56 */
    Biddy_Managed_ExistAbstract, /* 57 */
    Biddy_Managed_UnivAbstract, /* 58 */
    Biddy_Managed_AndAbstract, /* 59 */
    Biddy_Managed_Constrain, /* 60 */
    Biddy_Managed_Simplify, /* 61 */
    Biddy_Managed_Support, /* 62 */
    Biddy_Managed_ReplaceByKeyword, /* 63 */
    Biddy_Managed_Change, /* 64 */
    Biddy_Managed_Subset, /* 65 */
    Biddy_Managed_IsOK, /* 66 */
    Biddy_Managed_GC, /* 67 */
    Biddy_Managed_Clean, /* 68 */
    Biddy_Managed_Purge, /* 69 */
    Biddy_Managed_PurgeAndReorder, /* 70 */
    Biddy_Managed_Refresh, /* 71 */
    Biddy_Managed_AddCache, /* 72 */
    Biddy_Managed_AddFormula, /* 73 */
    Biddy_Managed_FindFormula, /* 74 */
    Biddy_Managed_DeleteFormula, /* 75 */
    Biddy_Managed_DeleteIthFormula, /* 76 */
    Biddy_Managed_GetIthFormula, /* 77 */
    Biddy_Managed_GetIthFormulaName, /* 78 */
    Biddy_Managed_SwapWithHigher, /* 79 */
    Biddy_Managed_SwapWithLower, /* 80 */
    Biddy_Managed_Sifting, /* 81 */
    Biddy_Managed_Copy, /* 82 */
    Biddy_Managed_CopyFormula, /* 83 */
    Biddy_Managed_Eval, /* 84 */
    Biddy_Managed_Random, /* 85 */
    Biddy_Managed_RandomSet, /* 86 */

    Biddy_Managed_NodeNumber, /* 87 */
    Biddy_NodeMaxLevel, /* 88 */
    Biddy_NodeAvgLevel, /* 89 */
    Biddy_Managed_VariableTableNum, /* 90 */
    Biddy_Managed_NodeTableSize, /* 91 */
    Biddy_Managed_NodeTableBlockNumber, /* 92 */
    Biddy_Managed_NodeTableGenerated, /* 93 */
    Biddy_Managed_NodeTableMax, /* 94 */
    Biddy_Managed_NodeTableNum, /* 95 */
    Biddy_Managed_NodeTableNumVar, /* 96 */
    Biddy_Managed_NodeTableResizeNumber, /* 97 */
    Biddy_Managed_NodeTableFoaNumber, /* 98 */
    Biddy_Managed_NodeTableFindNumber, /* 99 */
    Biddy_Managed_NodeTableCompareNumber, /* 100 */
    Biddy_Managed_NodeTableAddNumber, /* 101 */
    Biddy_Managed_NodeTableGCNumber, /* 102 */
    Biddy_Managed_NodeTableGCTime, /* 103 */
    Biddy_Managed_NodeTableGCObsoleteNumber, /* 104 */
    Biddy_Managed_NodeTableSwapNumber, /* 105 */
    Biddy_Managed_NodeTableSiftingNumber, /* 106 */
    Biddy_Managed_NodeTableDRTime, /* 107 */
    Biddy_Managed_NodeTableITENumber, /* 108 */
    Biddy_Managed_NodeTableITERecursiveNumber, /* 109 */
    Biddy_Managed_NodeTableANDORNumber, /* 110 */
    Biddy_Managed_NodeTableANDORRecursiveNumber, /* 111 */
    Biddy_Managed_NodeTableXORNumber, /* 112 */
    Biddy_Managed_NodeTableXORRecursiveNumber, /* 113 */
    Biddy_Managed_FormulaTableNum, /* 114 */
    Biddy_Managed_ListUsed, /* 115 */
    Biddy_Managed_ListMaxLength, /* 116 */
    Biddy_Managed_ListAvgLength, /* 117 */
    Biddy_Managed_OPCacheSearch, /* 118 */
    Biddy_Managed_OPCacheFind, /* 119 */
    Biddy_Managed_OPCacheInsert, /* 120 */
    Biddy_Managed_OPCacheOverwrite, /* 121 */
    Biddy_Managed_NodeNumberPlain, /* 122 */
    Biddy_Managed_DependentVariableNumber, /* 123 */
    Biddy_Managed_NodeVarNumber, /* 124 */
    Biddy_Managed_CountComplemented, /* 125 */
    Biddy_Managed_CountPaths, /* 126 */
    Biddy_Managed_CountMinterm, /* 127 */
    Biddy_Managed_DensityFunction, /* 128 */
    Biddy_Managed_DensityBDD, /* 129 */
    Biddy_Managed_ReadMemoryInUse, /* 130 */
    Biddy_Managed_PrintInfo, /* 131 */

    Biddy_Managed_Eval0, /* 132 */
    Biddy_Managed_Eval1x, /* 133 */
    Biddy_Managed_Eval2, /* 134 */
    Biddy_Managed_ReadVerilogFile, /* 135 */
    Biddy_Managed_PrintfBDD, /* 136 */
    Biddy_Managed_WriteBDD, /* 137 */
    Biddy_Managed_PrintfTable, /* 138 */
    Biddy_Managed_WriteTable, /* 139 */
    Biddy_Managed_PrintfSOP, /* 140 */
    Biddy_Managed_WriteSOP, /* 141 */
    Biddy_Managed_WriteDot, /* 142 */
    Biddy_Managed_WriteBddview, /* 143 */

    Bddscout_GetActiveManager, /* 1 */
    Bddscout_ClearActiveManager, /* 2 */
    Bddscout_ChangeActiveManager, /* 3 */
};
