/**CHeaderFile*************************************************************
  PackageName [Bdd Scout]
  Synopsis    [Bdd Scout]

  FileName    [bddscoutDecls.h]
  Revision    [$Revision: 124 $]
  Date        [$Date: 2015-12-30 17:27:05 +0100 (sre, 30 dec 2015) $]
  Authors     [Robert Meolic (robert.meolic@um.si)]
  Description [Generated by genStubs.tcl, see http://wiki.tcl.tk/3358]
  SeeAlso     [bddscout.h, bddscout.decls, bddscoutStubInit.c, bddscoutStubLib.c]

  Copyright   [This file is part of Bdd Scout package.
               Copyright (C) 2008, 2015 UM-FERI
               UM-FERI, Smetanova ulica 17, SI-2000 Maribor, Slovenia

               Bdd Scout is free software; you can redistribute it and/or modify
               it under the terms of the GNU General Public License as
               published by the Free Software Foundation; either version 2
               of the License, or (at your option) any later version.

               Bdd Scout is distributed in the hope that it will be useful,
               but WITHOUT ANY WARRANTY; without even the implied warranty of
               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
               GNU General Public License for more details.

               You should have received a copy of the GNU General Public
               License along with this program; if not, write to the Free
               Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
               Boston, MA 02110-1301 USA.]
  ************************************************************************/

typedef struct BddscoutStubs {
    int magic;
    const struct BddscoutStubHooks *hooks;

    void (*biddy_Init) (); /* 1 */
    void (*biddy_Exit) (); /* 2 */
    Biddy_String (*biddy_About) (); /* 3 */
    Biddy_Edge (*biddy_GetThen) (Biddy_Edge f); /* 4 */
    Biddy_Edge (*biddy_GetElse) (Biddy_Edge f); /* 5 */
    Biddy_Variable (*biddy_GetTopVariable) (Biddy_Edge f); /* 6 */
    void (*biddy_SelectNode) (Biddy_Edge f); /* 7 */
    void (*biddy_DeselectNode) (Biddy_Edge f); /* 8 */
    Biddy_Boolean (*biddy_IsSelected) (Biddy_Edge f); /* 9 */
    void (*biddy_NodeSelect) (Biddy_Edge f); /* 10 */
    void (*biddy_NodeRepair) (Biddy_Edge f); /* 11 */
    Biddy_Edge (*biddy_NOT) (Biddy_Edge f); /* 12 */
    Biddy_Edge (*biddy_TransferMark) (Biddy_Edge f, Biddy_Boolean mark); /* 13 */
    Biddy_Edge (*biddy_Managed_GetConstantZero) (Biddy_Manager MNG); /* 14 */
    Biddy_Edge (*biddy_Managed_GetConstantOne) (Biddy_Manager MNG); /* 15 */
    Biddy_String (*biddy_Managed_GetVariableName) (Biddy_Manager MNG, Biddy_Variable v); /* 16 */
    Biddy_String (*biddy_Managed_GetTopVariableName) (Biddy_Manager MNG, Biddy_Edge f); /* 17 */
    char (*biddy_Managed_GetTopVariableChar) (Biddy_Manager MNG, Biddy_Edge f); /* 18 */
    void (*biddy_Managed_ResetVariablesValue) (Biddy_Manager MNG); /* 19 */
    void (*biddy_Managed_SetVariableValue) (Biddy_Manager MNG, Biddy_Variable v, Biddy_Edge f); /* 20 */
    Biddy_Boolean (*biddy_Managed_IsSmaller) (Biddy_Manager MNG, Biddy_Variable fv, Biddy_Variable gv); /* 21 */
    Biddy_Edge (*biddy_Managed_AddVariable) (Biddy_Manager MNG); /* 22 */
    Biddy_Edge (*biddy_Managed_AddVariableBelow) (Biddy_Manager MNG, Biddy_Variable v); /* 23 */
    Biddy_Edge (*biddy_Managed_AddVariableAbove) (Biddy_Manager MNG, Biddy_Variable v); /* 24 */
    Biddy_Edge (*biddy_Managed_FoaVariable) (Biddy_Manager MNG, Biddy_String x); /* 25 */
    Biddy_Edge (*biddy_Managed_FoaNode) (Biddy_Manager MNG, Biddy_Variable v, Biddy_Edge pf, Biddy_Edge pt, Biddy_Boolean garbageAllowed); /* 26 */
    Biddy_Edge (*biddy_Managed_ITE) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g, Biddy_Edge h); /* 27 */
    Biddy_Edge (*biddy_Managed_And) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 28 */
    Biddy_Edge (*biddy_Managed_Or) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 29 */
    Biddy_Edge (*biddy_Managed_Nand) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 30 */
    Biddy_Edge (*biddy_Managed_Nor) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 31 */
    Biddy_Edge (*biddy_Managed_Xor) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 32 */
    Biddy_Edge (*biddy_Managed_Xnor) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 33 */
    Biddy_Boolean (*biddy_Managed_Leq) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 34 */
    Biddy_Edge (*biddy_Managed_Intersect) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g); /* 35 */
    Biddy_Edge (*biddy_Managed_Restrict) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Variable v, Biddy_Edge value); /* 36 */
    Biddy_Edge (*biddy_Managed_Compose) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Variable v, Biddy_Edge g); /* 37 */
    Biddy_Edge (*biddy_Managed_E) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Variable v); /* 38 */
    Biddy_Edge (*biddy_Managed_A) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Variable v); /* 39 */
    Biddy_Boolean (*biddy_Managed_IsVariableDependent) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Variable v); /* 40 */
    Biddy_Edge (*biddy_Managed_ExistAbstract) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge cube); /* 41 */
    Biddy_Edge (*biddy_Managed_UnivAbstract) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge cube); /* 42 */
    Biddy_Edge (*biddy_Managed_AndAbstract) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge g, Biddy_Edge cube); /* 43 */
    Biddy_Edge (*biddy_Managed_Constrain) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge c); /* 44 */
    Biddy_Edge (*biddy_Managed_Simplify) (Biddy_Manager MNG, Biddy_Edge f, Biddy_Edge c); /* 45 */
    Biddy_Edge (*biddy_Managed_Support) (Biddy_Manager MNG, Biddy_Edge f); /* 46 */
    Biddy_Edge (*biddy_Managed_Replace) (Biddy_Manager MNG, Biddy_Edge f); /* 47 */
    Biddy_Boolean (*biddy_Managed_IsOK) (Biddy_Manager MNG, Biddy_Edge f); /* 48 */
    void (*biddy_Managed_Garbage) (Biddy_Manager MNG); /* 49 */
    void (*biddy_Managed_Clean) (Biddy_Manager MNG); /* 50 */
    void (*biddy_Managed_Purge) (Biddy_Manager MNG); /* 51 */
    void (*biddy_Managed_PurgeAndReorder) (Biddy_Manager MNG, Biddy_Edge f); /* 52 */
    void (*biddy_Managed_Refresh) (Biddy_Manager MNG, Biddy_Edge f); /* 53 */
    void (*biddy_Managed_ClearAll) (Biddy_Manager MNG); /* 54 */
    void (*biddy_Managed_AddCache) (Biddy_Manager MNG, Biddy_GCFunction gc); /* 55 */
    void (*biddy_Managed_AddFormula) (Biddy_Manager MNG, Biddy_String x, Biddy_Edge f, int count); /* 56 */
    Biddy_Boolean (*biddy_Managed_FindFormula) (Biddy_Manager MNG, Biddy_String x, Biddy_Edge *f); /* 57 */
    Biddy_Boolean (*biddy_Managed_DeleteFormula) (Biddy_Manager MNG, Biddy_String x); /* 58 */
    Biddy_Boolean (*biddy_Managed_DeleteIthFormula) (Biddy_Manager MNG, unsigned int i); /* 59 */
    Biddy_Edge (*biddy_Managed_GetIthFormula) (Biddy_Manager MNG, unsigned int i); /* 60 */
    Biddy_String (*biddy_Managed_GetIthFormulaName) (Biddy_Manager MNG, unsigned int i); /* 61 */
    Biddy_Variable (*biddy_Managed_SwapWithHigher) (Biddy_Manager MNG, Biddy_Variable v); /* 62 */
    Biddy_Variable (*biddy_Managed_SwapWithLower) (Biddy_Manager MNG, Biddy_Variable v); /* 63 */
    Biddy_Boolean (*biddy_Managed_Sifting) (Biddy_Manager MNG, Biddy_Edge f); /* 64 */

    unsigned int (*biddy_NodeNumber) (Biddy_Edge f); /* 65 */
    unsigned int (*biddy_NodeMaxLevel) (Biddy_Edge f); /* 66 */
    float (*biddy_NodeAvgLevel) (Biddy_Edge f); /* 67 */
    Biddy_Variable (*biddy_Managed_VariableTableNum) (Biddy_Manager MNG); /* 68 */
    unsigned int (*biddy_Managed_NodeTableSize) (Biddy_Manager MNG); /* 69 */
    unsigned int (*biddy_Managed_NodeTableMax) (Biddy_Manager MNG); /* 70 */
    unsigned int (*biddy_Managed_NodeTableNum) (Biddy_Manager MNG); /* 71 */
    unsigned int (*biddy_Managed_NodeTableNumVar) (Biddy_Manager MNG, Biddy_Variable v); /* 72 */
    unsigned int (*biddy_Managed_NodeTableNumF) (Biddy_Manager MNG); /* 73 */
    unsigned long long int (*biddy_Managed_NodeTableFOA) (Biddy_Manager MNG); /* 74 */
    unsigned long long int (*biddy_Managed_NodeTableCompare) (Biddy_Manager MNG); /* 75 */
    unsigned long long int (*biddy_Managed_NodeTableAdd) (Biddy_Manager MNG); /* 76 */
    unsigned int (*biddy_Managed_NodeTableGarbage) (Biddy_Manager MNG); /* 77 */
    unsigned int (*biddy_Managed_NodeTableGenerated) (Biddy_Manager MNG); /* 78 */
    unsigned int (*biddy_Managed_NodeTableBlockNumber) (Biddy_Manager MNG); /* 79 */
    unsigned int (*biddy_Managed_NodeTableSwapNumber) (Biddy_Manager MNG); /* 80 */
    unsigned int (*biddy_Managed_NodeTableSiftingNumber) (Biddy_Manager MNG); /* 81 */
    unsigned int (*biddy_Managed_ListUsed) (Biddy_Manager MNG); /* 82 */
    unsigned int (*biddy_Managed_ListMaxLength) (Biddy_Manager MNG); /* 83 */
    float (*biddy_Managed_ListAvgLength) (Biddy_Manager MNG); /* 84 */
    unsigned long long int (*biddy_Managed_IteCacheSearch) (Biddy_Manager MNG); /* 85 */
    unsigned long long int (*biddy_Managed_IteCacheFind) (Biddy_Manager MNG); /* 86 */
    unsigned long long int (*biddy_Managed_IteCacheOverwrite) (Biddy_Manager MNG); /* 87 */
    unsigned int (*biddy_Managed_NodeNumberPlain) (Biddy_Manager MNG, Biddy_Edge f); /* 88 */
    unsigned int (*biddy_Managed_VariableNumber) (Biddy_Manager MNG, Biddy_Edge f); /* 89 */
    void (*biddy_Managed_NodeVarNumber) (Biddy_Manager MNG, Biddy_Edge f, unsigned int *n, unsigned int *v); /* 90 */
    double (*biddy_Managed_CountMinterm) (Biddy_Manager MNG, Biddy_Edge f, unsigned int nvars); /* 91 */
    unsigned long long int (*biddy_Managed_ReadMemoryInUse) (Biddy_Manager MNG); /* 92 */
    void (*biddy_Managed_PrintInfo) (Biddy_Manager MNG, FILE *f); /* 93 */

    Biddy_String (*biddy_Managed_Eval0) (Biddy_Manager MNG, Biddy_String s); /* 94 */
    Biddy_Edge (*biddy_Managed_Eval1) (Biddy_Manager MNG, Biddy_String s); /* 95 */
    Biddy_Edge (*biddy_Managed_Eval1x) (Biddy_Manager MNG, Biddy_String s, Biddy_LookupFunction lf); /* 96 */
    Biddy_Edge (*biddy_Managed_Eval2) (Biddy_Manager MNG, Biddy_String boolFunc); /* 97 */
    void (*biddy_Managed_WriteBDD) (Biddy_Manager MNG, Biddy_Edge f); /* 98 */
    void (*biddy_Managed_WriteBDDx) (Biddy_Manager MNG, const char filename[], Biddy_Edge f, Biddy_String label); /* 99 */
    unsigned int (*biddy_Managed_WriteDot) (Biddy_Manager MNG, const char filename[], Biddy_Edge f, const char label[]); /* 100 */
    unsigned int (*biddy_Managed_WriteDotx) (Biddy_Manager MNG, const char filename[], Biddy_Edge f, const char label[], int id); /* 101 */
    void (*biddy_Managed_WriteTable) (Biddy_Manager MNG, Biddy_Edge f); /* 102 */

} BddscoutStubs;

#ifdef __cplusplus
extern "C" {
#endif
extern const BddscoutStubs *bddscoutStubsPtr;
#ifdef __cplusplus
}
#endif

#if defined(USE_BDDSCOUT_STUBS)

#define Biddy_Init \
	(bddscoutStubsPtr->biddy_Init) /* 1 */
#define Biddy_Exit \
	(bddscoutStubsPtr->biddy_Exit) /* 2 */
#define Biddy_About \
	(bddscoutStubsPtr->biddy_About) /* 3 */
#define Biddy_GetThen \
	(bddscoutStubsPtr->biddy_GetThen) /* 4 */
#define Biddy_GetElse \
	(bddscoutStubsPtr->biddy_GetElse) /* 5 */
#define Biddy_GetTopVariable \
	(bddscoutStubsPtr->biddy_GetTopVariable) /* 6 */
#define Biddy_SelectNode \
	(bddscoutStubsPtr->biddy_SelectNode) /* 7 */
#define Biddy_DeselectNode \
	(bddscoutStubsPtr->biddy_DeselectNode) /* 8 */
#define Biddy_IsSelected \
	(bddscoutStubsPtr->biddy_IsSelected) /* 9 */
#define Biddy_NodeSelect \
	(bddscoutStubsPtr->biddy_NodeSelect) /* 10 */
#define Biddy_NodeRepair \
	(bddscoutStubsPtr->biddy_NodeRepair) /* 11 */
#define Biddy_NOT \
	(bddscoutStubsPtr->biddy_NOT) /* 12 */
#define Biddy_TransferMark \
	(bddscoutStubsPtr->biddy_TransferMark) /* 13 */
#define Biddy_Managed_GetConstantZero \
	(bddscoutStubsPtr->biddy_Managed_GetConstantZero) /* 14 */
#define Biddy_Managed_GetConstantOne \
	(bddscoutStubsPtr->biddy_Managed_GetConstantOne) /* 15 */
#define Biddy_Managed_GetVariableName \
	(bddscoutStubsPtr->biddy_Managed_GetVariableName) /* 16 */
#define Biddy_Managed_GetTopVariableName \
	(bddscoutStubsPtr->biddy_Managed_GetTopVariableName) /* 17 */
#define Biddy_Managed_GetTopVariableChar \
	(bddscoutStubsPtr->biddy_Managed_GetTopVariableChar) /* 18 */
#define Biddy_Managed_ResetVariablesValue \
	(bddscoutStubsPtr->biddy_Managed_ResetVariablesValue) /* 19 */
#define Biddy_Managed_SetVariableValue \
	(bddscoutStubsPtr->biddy_Managed_SetVariableValue) /* 20 */
#define Biddy_Managed_IsSmaller \
	(bddscoutStubsPtr->biddy_Managed_IsSmaller) /* 21 */
#define Biddy_Managed_AddVariable \
	(bddscoutStubsPtr->biddy_Managed_AddVariable) /* 22 */
#define Biddy_Managed_AddVariableBelow \
	(bddscoutStubsPtr->biddy_Managed_AddVariableBelow) /* 23 */
#define Biddy_Managed_AddVariableAbove \
	(bddscoutStubsPtr->biddy_Managed_AddVariableAbove) /* 24 */
#define Biddy_Managed_FoaVariable \
	(bddscoutStubsPtr->biddy_Managed_FoaVariable) /* 25 */
#define Biddy_Managed_FoaNode \
	(bddscoutStubsPtr->biddy_Managed_FoaNode) /* 26 */
#define Biddy_Managed_ITE \
	(bddscoutStubsPtr->biddy_Managed_ITE) /* 27 */
#define Biddy_Managed_And \
	(bddscoutStubsPtr->biddy_Managed_And) /* 28 */
#define Biddy_Managed_Or \
	(bddscoutStubsPtr->biddy_Managed_Or) /* 29 */
#define Biddy_Managed_Nand \
	(bddscoutStubsPtr->biddy_Managed_Nand) /* 30 */
#define Biddy_Managed_Nor \
	(bddscoutStubsPtr->biddy_Managed_Nor) /* 31 */
#define Biddy_Managed_Xor \
	(bddscoutStubsPtr->biddy_Managed_Xor) /* 32 */
#define Biddy_Managed_Xnor \
	(bddscoutStubsPtr->biddy_Managed_Xnor) /* 33 */
#define Biddy_Managed_Leq \
	(bddscoutStubsPtr->biddy_Managed_Leq) /* 34 */
#define Biddy_Managed_Intersect \
	(bddscoutStubsPtr->biddy_Managed_Intersect) /* 35 */
#define Biddy_Managed_Restrict \
	(bddscoutStubsPtr->biddy_Managed_Restrict) /* 36 */
#define Biddy_Managed_Compose \
	(bddscoutStubsPtr->biddy_Managed_Compose) /* 37 */
#define Biddy_Managed_E \
	(bddscoutStubsPtr->biddy_Managed_E) /* 38 */
#define Biddy_Managed_A \
	(bddscoutStubsPtr->biddy_Managed_A) /* 39 */
#define Biddy_Managed_IsVariableDependent \
	(bddscoutStubsPtr->biddy_Managed_IsVariableDependent) /* 40 */
#define Biddy_Managed_ExistAbstract \
	(bddscoutStubsPtr->biddy_Managed_ExistAbstract) /* 41 */
#define Biddy_Managed_UnivAbstract \
	(bddscoutStubsPtr->biddy_Managed_UnivAbstract) /* 42 */
#define Biddy_Managed_AndAbstract \
	(bddscoutStubsPtr->biddy_Managed_AndAbstract) /* 43 */
#define Biddy_Managed_Constrain \
	(bddscoutStubsPtr->biddy_Managed_Constrain) /* 44 */
#define Biddy_Managed_Simplify \
	(bddscoutStubsPtr->biddy_Managed_Simplify) /* 45 */
#define Biddy_Managed_Support \
	(bddscoutStubsPtr->biddy_Managed_Support) /* 46 */
#define Biddy_Managed_Replace \
	(bddscoutStubsPtr->biddy_Managed_Replace) /* 47 */
#define Biddy_Managed_IsOK \
	(bddscoutStubsPtr->biddy_Managed_IsOK) /* 48 */
#define Biddy_Managed_Garbage \
	(bddscoutStubsPtr->biddy_Managed_Garbage) /* 49 */
#define Biddy_Managed_Clean \
	(bddscoutStubsPtr->biddy_Managed_Clean) /* 50 */
#define Biddy_Managed_Purge \
	(bddscoutStubsPtr->biddy_Managed_Purge) /* 51 */
#define Biddy_Managed_PurgeAndReorder \
	(bddscoutStubsPtr->biddy_Managed_PurgeAndReorder) /* 52 */
#define Biddy_Managed_Refresh \
	(bddscoutStubsPtr->biddy_Managed_Refresh) /* 53 */
#define Biddy_Managed_ClearAll \
	(bddscoutStubsPtr->biddy_Managed_ClearAll) /* 54 */
#define Biddy_Managed_AddCache \
	(bddscoutStubsPtr->biddy_Managed_AddCache) /* 55 */
#define Biddy_Managed_AddFormula \
	(bddscoutStubsPtr->biddy_Managed_AddFormula) /* 56 */
#define Biddy_Managed_FindFormula \
	(bddscoutStubsPtr->biddy_Managed_FindFormula) /* 57 */
#define Biddy_Managed_DeleteFormula \
	(bddscoutStubsPtr->biddy_Managed_DeleteFormula) /* 58 */
#define Biddy_Managed_DeleteIthFormula \
	(bddscoutStubsPtr->biddy_Managed_DeleteIthFormula) /* 59 */
#define Biddy_Managed_GetIthFormula \
	(bddscoutStubsPtr->biddy_Managed_GetIthFormula) /* 60 */
#define Biddy_Managed_GetIthFormulaName \
	(bddscoutStubsPtr->biddy_Managed_GetIthFormulaName) /* 61 */
#define Biddy_Managed_SwapWithHigher \
	(bddscoutStubsPtr->biddy_Managed_SwapWithHigher) /* 62 */
#define Biddy_Managed_SwapWithLower \
	(bddscoutStubsPtr->biddy_Managed_SwapWithLower) /* 63 */
#define Biddy_Managed_Sifting \
	(bddscoutStubsPtr->biddy_Managed_Sifting) /* 64 */

#define Biddy_NodeNumber \
	(bddscoutStubsPtr->biddy_NodeNumber) /* 65 */
#define Biddy_NodeMaxLevel \
	(bddscoutStubsPtr->biddy_NodeMaxLevel) /* 66 */
#define Biddy_NodeAvgLevel \
	(bddscoutStubsPtr->biddy_NodeAvgLevel) /* 67 */
#define Biddy_Managed_VariableTableNum \
	(bddscoutStubsPtr->biddy_Managed_VariableTableNum) /* 68 */
#define Biddy_Managed_NodeTableSize \
	(bddscoutStubsPtr->biddy_Managed_NodeTableSize) /* 69 */
#define Biddy_Managed_NodeTableMax \
	(bddscoutStubsPtr->biddy_Managed_NodeTableMax) /* 70 */
#define Biddy_Managed_NodeTableNum \
	(bddscoutStubsPtr->biddy_Managed_NodeTableNum) /* 71 */
#define Biddy_Managed_NodeTableNumVar \
	(bddscoutStubsPtr->biddy_Managed_NodeTableNumVar) /* 72 */
#define Biddy_Managed_NodeTableNumF \
	(bddscoutStubsPtr->biddy_Managed_NodeTableNumF) /* 73 */
#define Biddy_Managed_NodeTableFOA \
	(bddscoutStubsPtr->biddy_Managed_NodeTableFOA) /* 74 */
#define Biddy_Managed_NodeTableCompare \
	(bddscoutStubsPtr->biddy_Managed_NodeTableCompare) /* 75 */
#define Biddy_Managed_NodeTableAdd \
	(bddscoutStubsPtr->biddy_Managed_NodeTableAdd ) /* 76 */
#define Biddy_Managed_NodeTableGarbage \
	(bddscoutStubsPtr->biddy_Managed_NodeTableGarbage) /* 77 */
#define Biddy_Managed_NodeTableGenerated \
	(bddscoutStubsPtr->biddy_Managed_NodeTableGenerated) /* 78 */
#define Biddy_Managed_NodeTableBlockNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableBlockNumber) /* 79 */
#define Biddy_Managed_NodeTableSwapNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableSwapNumber) /* 80 */
#define Biddy_Managed_NodeTableSiftingNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeTableSiftingNumber) /* 81 */
#define Biddy_Managed_ListUsed \
	(bddscoutStubsPtr->biddy_Managed_ListUsed) /* 82 */
#define Biddy_Managed_ListMaxLength \
	(bddscoutStubsPtr->biddy_Managed_ListMaxLength) /* 83 */
#define Biddy_Managed_ListAvgLength \
	(bddscoutStubsPtr->biddy_Managed_ListAvgLength) /* 84 */
#define Biddy_Managed_IteCacheSearch \
	(bddscoutStubsPtr->biddy_Managed_IteCacheSearch) /* 85 */
#define Biddy_Managed_IteCacheFind \
	(bddscoutStubsPtr->biddy_Managed_IteCacheFind) /* 86 */
#define Biddy_Managed_IteCacheOverwrite \
	(bddscoutStubsPtr->biddy_Managed_IteCacheOverwrite) /* 87 */
#define Biddy_Managed_NodeNumberPlain \
	(bddscoutStubsPtr->biddy_Managed_NodeNumberPlain) /* 88 */
#define Biddy_Managed_VariableNumber \
	(bddscoutStubsPtr->biddy_Managed_VariableNumber) /* 89 */
#define Biddy_Managed_NodeVarNumber \
	(bddscoutStubsPtr->biddy_Managed_NodeVarNumber) /* 90 */
#define Biddy_Managed_CountMinterm \
	(bddscoutStubsPtr->biddy_Managed_CountMinterm) /* 91 */
#define Biddy_Managed_ReadMemoryInUse \
	(bddscoutStubsPtr->biddy_Managed_ReadMemoryInUse) /* 92 */
#define Biddy_Managed_PrintInfo \
	(bddscoutStubsPtr->biddy_Managed_PrintInfo) /* 93 */

#define Biddy_Managed_Eval0 \
	(bddscoutStubsPtr->biddy_Managed_Eval0) /* 94 */
#define Biddy_Managed_Eval1 \
	(bddscoutStubsPtr->biddy_Managed_Eval1) /* 95 */
#define Biddy_Managed_Eval1x \
	(bddscoutStubsPtr->biddy_Managed_Eval1x) /* 96 */
#define Biddy_Managed_Eval2 \
	(bddscoutStubsPtr->biddy_Managed_Eval2) /* 97 */
#define Biddy_Managed_WriteBDD \
	(bddscoutStubsPtr->biddy_Managed_WriteBDD) /* 98 */
#define Biddy_Managed_WriteBDDx \
	(bddscoutStubsPtr->biddy_Managed_WriteBDDx) /* 99 */
#define Biddy_Managed_WriteDot \
	(bddscoutStubsPtr->biddy_Managed_WriteDot) /* 100 */
#define Biddy_Managed_WriteDotx \
	(bddscoutStubsPtr->biddy_Managed_WriteDotx) /* 101 */
#define Biddy_Managed_WriteTable \
	(bddscoutStubsPtr->biddy_Managed_WriteTable) /* 102 */

#endif /* defined(USE_BDDSCOUT_STUBS) */
