#!/bin/bash

#  Authors     [Robert Meolic (robert@meolic.com)]
#  Revision    [$Revision: 631 $]
#  Date        [$Date: 2020-05-09 09:42:48 +0200 (sob, 09 maj 2020) $]
#
#  Copyright   [This file is part of Bdd Scout package.
#               Copyright (C) 2008, 2019 UM FERI, Koroska cesta 46, SI-2000 Maribor, Slovenia
#               Copyright (C) 2019, 2020 Robert Meolic, SI-2000 Maribor, Slovenia
#
#               Biddy is free software; you can redistribute it and/or modify
#               it under the terms of the GNU General Public License as
#               published by the Free Software Foundation; either version 2
#               of the License, or (at your option) any later version.
#
#               Biddy is distributed in the hope that it will be useful,
#               but WITHOUT ANY WARRANTY; without even the implied warranty of
#               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#               GNU General Public License for more details.
#
#               You should have received a copy of the GNU General Public
#               License along with this program; if not, write to the Free
#               Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#               Boston, MA 02110-1301 USA.]

# We are using dch -M
# remove -M if you are not the author of the last changelog entry

# Some help on building deb packages:
# http://wiki.debian.org/Packaging
# http://wiki.debian.org/IntroDebianPackaging
# http://packaging.ubuntu.com/html/

# Some help on using pbuilder
# https://wiki.ubuntu.com/PbuilderHowto
# http://wiki.debian.org/PbuilderTricks

# 1. To use pbuilder-dist you have to initialize/update pbuilder as follows:
# pbuilder-dist focal create
# pbuilder-dist focal update

# 2. We are using biddy package from Ubuntu ppa.
# You can check it on https://launchpad.net/~meolic/+archive/ubuntu/biddy
# To add this ppa to your pbuilder environment, do the following:
# pbuilder-dist focal login --save-after-login
# You will get root prompt and then do the following:
# apt-get install gnupg2 (this seems to be needed for artful, bionic, and laters)
# apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9018C2C6
# exit

# 3. You have to get the latest biddy library. Do the following:
# pbuilder-dist focal update --override-config --othermirror "deb http://ppa.launchpad.net/meolic/biddy/ubuntu focal main"

# DO NOT USE (= 1.X) FOR libbiddy IN YOUR control FILE
# FOR ME, THE PACKAGE IS CORRECTLY BUILDED ONLY IF I USE (>= 1.X)

VERSION=`sed "" VERSION`
NAME="bddscout"
OS=`uname | sed "s/_.*//;s/[0-9]//g"`
DISTRO=$(lsb_release --short --codename)

if [ $# != 1 ]
then
  echo "Usage: ./package-deb RELEASE_NUMBER"
  exit 0
else
  RELEASE=$1
fi

if [ ! -d "../distribution-bddscout/version-$VERSION" ]
then
  echo "CREATE TGZ PACKAGE FIRST!"
  exit 0
fi

if [ -e "../distribution-bddscout/version-$VERSION/release-$RELEASE" ]
then
  echo "CANNOT CHANGE AN EXISTING RELEASE!"
  exit 0
fi

echo ""
echo "************************"
echo "CREATING NEW RELEASE ..."
echo "************************"
echo ""

mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE"
mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/create"
mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/scripts"
mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian"
mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian/source"
cp debian/compat "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian"
cp debian/control "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian"
cp debian/copyright "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian"
cp debian/bddscout.dirs "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian"
cp debian/bddscout-ifip.dirs "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian"
cp debian/bddscout-ifip-data.dirs "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian"
cp debian/bddscout-bra.dirs "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian"
cp debian/bddscout-bddtraces.dirs "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian"
cp debian/bddscout-bddtraces-data.dirs "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian"
cp debian/rules "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian"
cp debian/source/format "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/debian/source"

cp VERSION README README.Linux CHANGES "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp bddscout.h bddscoutTcl.h bddscout.c bddscoutTcl.c bddscoutMain.c bddscout.tcl "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp bddscoutDecls.h bddscoutStubInit.c bddscoutStubLib.c "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp pkgIndex.tcl "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp bddscoutIFIP.c bddscoutIFIP.tcl "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp pkgExtensionIFIP.tcl "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp bddscoutBRA.c bddscoutBRA.tcl "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp pkgExtensionBRA.tcl "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp bddscoutBDDTRACES.c bddtraces-BIDDY.c bddscoutBDDTRACES.tcl "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp pkgExtensionBDDTRACES.tcl "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp Makefile Makefile.Linux bddscout.map "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp example.bdd example.bf "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp create/*.tcl "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/create"
cp scripts/*.tcl "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION/scripts"
cp ../bddview/bddview.tcl "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp ../bddview/example-robdd.bddview "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp ../bddview/example-robddce.bddview "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp ../bddview/example-zbddce.bddview "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp ../bddview/example-tzbdd.bddview "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/IFIP
mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/IFIP/cath
mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/IFIP/ex
mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/IFIP/hachtel
mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/IFIP/plasco
cp IFIP/README IFIP/*.txt "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/IFIP
cp IFIP/cath/* "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/IFIP/cath
cp IFIP/ex/* "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/IFIP/ex
cp IFIP/hachtel/* "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/IFIP/hachtel
cp IFIP/plasco/* "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/IFIP/plasco
mkdir "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/BDDTRACES
cp BDDTRACES/* "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"/BDDTRACES

pushd "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
cp "../../changelog.deb" "debian/changelog"
cd ..
tar -czf "$NAME-$VERSION.tar.gz" "$NAME-$VERSION"
mv "$NAME-$VERSION.tar.gz" "$NAME"_"$VERSION.orig.tar.gz"
cd "$NAME-$VERSION"

echo ""
echo "**************************"
echo "GENERATING SOURCE PACKAGES"
echo "used to mantain Ubuntu PPA"
echo "**************************"
echo ""

# create a source distribution which match your system
# it will be builded in "distribution/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
# change key (debuild -k) if you are not Robert Meolic
echo "GENERATING SOURCE PACKAGE FOR $DISTRO"
dch -M -v "$VERSION-$RELEASE" -D $DISTRO
cp "debian/changelog" "../../changelog.deb"
debuild -d -S -sa -kF7FCCB3CD22F409B
mkdir `pwd`/../$DISTRO
mkdir `pwd`/../$DISTRO/source
mv `pwd`/../*.changes `pwd`/../*.dsc `pwd`/../$DISTRO/source/
mv `pwd`/../*.debian.tar.xz `pwd`/../$DISTRO/source
mv `pwd`/../*.build `pwd`/../$DISTRO/source
mv `pwd`/../*.buildinfo `pwd`/../$DISTRO/source
cp `pwd`/../*.orig.tar.gz `pwd`/../$DISTRO/source/

# create a source distribution for xenial
# it will be builded in "distribution/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
# change key (debuild -k) if you are not Robert Meolic
ALTDISTRO=bionic
echo "GENERATING SOURCE PACKAGE FOR $ALTDISTRO"
cp "../../changelog.deb" "debian/changelog"
dch -M -l"~$ALTDISTRO" -D $ALTDISTRO
debuild -d -S -sa -kF7FCCB3CD22F409B
mkdir `pwd`/../$ALTDISTRO
mkdir `pwd`/../$ALTDISTRO/source
mv `pwd`/../*.changes `pwd`/../*.dsc `pwd`/../$ALTDISTRO/source
mv `pwd`/../*.debian.tar.xz `pwd`/../$ALTDISTRO/source
mv `pwd`/../*.build `pwd`/../$ALTDISTRO/source
mv `pwd`/../*.buildinfo `pwd`/../$ALTDISTRO/source
cp `pwd`/../*.orig.tar.gz `pwd`/../$ALTDISTRO/source

# create a source distribution for cosmic
# it will be builded in "distribution/version-$VERSION/release-$RELEASE/$NAME-$VERSION"
# change key (debuild -k) if you are not Robert Meolic
ALTDISTRO=eoan
echo "GENERATING SOURCE PACKAGE FOR $ALTDISTRO"
cp "../../changelog.deb" "debian/changelog"
dch -M -l"~$ALTDISTRO" -D $ALTDISTRO
debuild -d -S -sa -kF7FCCB3CD22F409B
mkdir `pwd`/../$ALTDISTRO
mkdir `pwd`/../$ALTDISTRO/source
mv `pwd`/../*.changes `pwd`/../*.dsc `pwd`/../$ALTDISTRO/source
mv `pwd`/../*.debian.tar.xz `pwd`/../$ALTDISTRO/source
mv `pwd`/../*.build `pwd`/../$ALTDISTRO/source
mv `pwd`/../*.buildinfo `pwd`/../$ALTDISTRO/source
cp `pwd`/../*.orig.tar.gz `pwd`/../$ALTDISTRO/source

cd ..

echo ""
echo "************************"
echo "GENERATING DEB PACKAGES "
echo "************************"
echo ""

# all target pbuilder environments must already exists
# use e.g pbuilder-dist artful create
# use e.g pbuilder-dist artful update

echo "BUILDING FOR YOUR DISTRO: $DISTRO"
pbuilder-dist $DISTRO build --buildresult `pwd`/$DISTRO `pwd`/$DISTRO/source/*.dsc

ALTDISTRO=bionic
echo "BUILDING FOR $ALTDISTRO"
pbuilder-dist $ALTDISTRO build --buildresult `pwd`/$ALTDISTRO `pwd`/$ALTDISTRO/source/*.dsc

ALTDISTRO=eoan
echo "BUILDING FOR $ALTDISTRO"
pbuilder-dist $ALTDISTRO build --buildresult `pwd`/$ALTDISTRO `pwd`/$ALTDISTRO/source/*.dsc

popd
rm -fr "../distribution-bddscout/version-$VERSION/release-$RELEASE/$NAME-$VERSION"

echo ""
echo "*******************"
echo "PACKAGES COMPLETED!"
echo "*******************"
echo ""
