#!/bin/bash

#  Authors     [Robert Meolic (robert@meolic.com)]
#  Revision    [$Revision: 698 $]
#  Date        [$Date: 2024-07-09 16:35:11 +0200 (tor, 09 jul 2024) $]
#
#  Copyright   [This file is part of Bdd Scout package.
#               Copyright (C) 2008, 2019 UM FERI, Koroska cesta 46, SI-2000 Maribor, Slovenia
#               Copyright (C) 2019, 2024 Robert Meolic, SI-2000 Maribor, Slovenia
#
#               Biddy is free software; you can redistribute it and/or modify
#               it under the terms of the GNU General Public License as
#               published by the Free Software Foundation; either version 2
#               of the License, or (at your option) any later version.
#
#               Biddy is distributed in the hope that it will be useful,
#               but WITHOUT ANY WARRANTY; without even the implied warranty of
#               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#               GNU General Public License for more details.
#
#               You should have received a copy of the GNU General Public
#               License along with this program; if not, write to the Free
#               Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#               Boston, MA 02110-1301 USA.]

# to change editor used for commit, run 'select-editor'.

VERSION=`sed "" ../VERSION`
NAME="bddscout"
OS=`uname | sed "s/_.*//;s/[0-9]//g"`
DISTRO=$(lsb_release --short --codename)

mkdir -p "../distribution-bddscout"

if [ -e "../distribution-bddscout/version-$VERSION" ]
then
  echo "CANNOT CHANGE AN EXISTING VERSION!"
  exit 0
fi

echo ""
echo "************************"
echo "CREATING NEW VERSION ..."
echo "************************"
echo ""

mkdir "../distribution-bddscout/version-$VERSION"
mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION/create"
mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION/scripts"

cp VERSION CHANGES COPYING "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp README README.Linux "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp bddscout.h bddscoutTcl.h bddscout.c bddscoutTcl.c bddscoutMain.c bddscout.tcl "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp pkgIndex.tcl "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp bddscoutIFIP.c bddscoutIFIP.tcl "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp pkgExtensionIFIP.tcl "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp bddscoutBRA.c bddscoutBRA.tcl "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp pkgExtensionBRA.tcl "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp bddscoutBDDTRACES.c bddtraces-BIDDY.c bddscoutBDDTRACES.tcl "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp pkgExtensionBDDTRACES.tcl "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp Makefile Makefile.Linux bddscout.map "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp example.bdd example.bf "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp create/*.tcl "../distribution-bddscout/version-$VERSION/$NAME-$VERSION/create"
cp scripts/*.tcl "../distribution-bddscout/version-$VERSION/$NAME-$VERSION/scripts"
cp ../bddview/bddview.tcl "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp ../bddview/example-robdd.bddview "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp ../bddview/example-robddce.bddview "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp ../bddview/example-zbddce.bddview "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
cp ../bddview/example-tzbdd.bddview "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/IFIP
mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/IFIP/cath
mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/IFIP/ex
mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/IFIP/hachtel
mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/IFIP/plasco
cp IFIP/README IFIP/*.txt "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/IFIP
cp IFIP/cath/* "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/IFIP/cath
cp IFIP/ex/* "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/IFIP/ex
cp IFIP/hachtel/* "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/IFIP/hachtel
cp IFIP/plasco/* "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/IFIP/plasco
mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/BDDTRACES
cp BDDTRACES/* "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/BDDTRACES

mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/debian
mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/debian/source
cp debian/c* "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/debian
cp debian/r* "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/debian
cp debian/*.dirs "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/debian
cp debian/source/* "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/debian/source

pushd "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"
# change distribution name if needed
dch -M --create --package "$NAME" -v "$VERSION" -D $DISTRO
cp "debian/changelog" "../changelog.deb"
popd

mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/rpm
mkdir "../distribution-bddscout/version-$VERSION/$NAME-$VERSION"/rpm/SPECS
sed -e "s/THISVERSION/$VERSION/g" -e "s/THISRELEASE/0/g" \
    "rpm/SPECS/bddscout.spec" \
    > "../distribution-bddscout/version-$VERSION/$NAME-$VERSION/rpm/SPECS/bddscout.spec"

pushd "../distribution-bddscout/version-$VERSION"
echo "* `LC_ALL=en_GB date +"%a %b %d %Y"` - meolic" > changelog.rpm
echo "- Initial release." >> changelog.rpm
vi changelog.rpm
popd

pushd "../distribution-bddscout/version-$VERSION"
tar -czf "$NAME-$VERSION.tar.gz" "$NAME-$VERSION"
mv "$NAME-$VERSION.tar.gz" "$NAME"_"$VERSION.initial.tar.gz"
rm -fr "$NAME-$VERSION"
popd

echo ""
echo "**********************"
echo "TGZ PACKAGE COMPLETED!"
echo "**********************"
echo ""
