#!/bin/bash

#  Authors     [Robert Meolic (robert@meolic.com)]
#  Revision    [$Revision: 545 $]
#  Date        [$Date: 2019-02-11 14:07:50 +0100 (pon, 11 feb 2019) $]
#
#  Copyright   [This file is part of Bdd Scout package.
#               Copyright (C) 2008, 2019 UM FERI
#               UM FERI, Koroska cesta 46, SI-2000 Maribor, Slovenia
#
#               Bdd Scout is free software; you can redistribute it and/or modify
#               it under the terms of the GNU General Public License as
#               published by the Free Software Foundation; either version 2
#               of the License, or (at your option) any later version.
#
#               Bdd Scout is distributed in the hope that it will be useful,
#               but WITHOUT ANY WARRANTY; without even the implied warranty of
#               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#               GNU General Public License for more details.
#
#               You should have received a copy of the GNU General Public
#               License along with this program; if not, write to the Free
#               Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
#               Boston, MA 02110-1301 USA.]

# use CFLAGS="-m32" to produce 32-bit libs
# use CFLAGS="-m64" to produce 64-bit libs
# leave empty for system default
CFLAGS+=""

NAME="bddscout"
VERSION=`sed "s|\.|-|g" VERSION`
OS=`uname | sed "s/_.*//;s/[0-9]//g"`

if [ $OS = "Linux" ] ; then
  osbiddylibext="./bddscout.so"
fi

if [ $OS = "SunOS" ] ; then
  osbiddylibext="./bddscout.so"
fi

if [ $OS = "Darwin" ] ; then
  osbiddylibext="-L. -lbddscout"
fi

if [ $OS = "MINGW" ] ; then
  osbiddylibext="-L. -lbddscout"
fi

rm -f "$NAME-bin-$VERSION-$OS.zip"
rm -f "$NAME-$VERSION-$OS.zip"

rm -fr ./$NAME-$VERSION

echo "*** Building Biddy ..."
cd ..
make static "CFLAGS = $CFLAGS" "BINDIR = ./bddscout/$NAME-$VERSION"
make clean "BINDIR = ./bddscout/$NAME-$VERSION"
cp biddy.h ./bddscout/$NAME-$VERSION
cp CHANGES ./bddscout/$NAME-$VERSION/CHANGES_biddy
echo "*** Biddy OK."

echo "*** Preparing bddview ..."
cd bddview
cp bddview.tcl ../bddscout/$NAME-$VERSION
cp CHANGES ../bddscout/$NAME-$VERSION/CHANGES_bddview
cp example-robdd.bddview ../bddscout/$NAME-$VERSION
cp example-robddce.bddview ../bddscout/$NAME-$VERSION
cp example-zbddce.bddview ../bddscout/$NAME-$VERSION
cp example-tzbdd.bddview ../bddscout/$NAME-$VERSION
echo "*** bddview OK."

echo "*** Building BDD Scout ..."
cd ../bddscout
cp bddscout.h ./$NAME-$VERSION
cp bddscoutTcl.h ./$NAME-$VERSION
cp bddscout.c ./$NAME-$VERSION
cp bddscoutTcl.c ./$NAME-$VERSION
cp bddscoutMain.c ./$NAME-$VERSION
cp bddscout.tcl ./$NAME-$VERSION
cp bddscoutDecls.h ./$NAME-$VERSION
cp bddscoutStubInit.c ./$NAME-$VERSION
cp bddscoutStubLib.c ./$NAME-$VERSION
cp pkgIndex.tcl ./$NAME-$VERSION
cp bddscoutIFIP.c ./$NAME-$VERSION
cp bddscoutIFIP.tcl ./$NAME-$VERSION
cp pkgExtensionIFIP.tcl ./$NAME-$VERSION
cp bddscoutBRA.c ./$NAME-$VERSION
cp bddscoutBRA.tcl ./$NAME-$VERSION
cp pkgExtensionBRA.tcl ./$NAME-$VERSION
cp bddscoutBDDTRACES.c ./$NAME-$VERSION
cp bddtraces-BIDDY.c ./$NAME-$VERSION
cp bddscoutBDDTRACES.tcl ./$NAME-$VERSION
cp pkgExtensionBDDTRACES.tcl ./$NAME-$VERSION
cp Makefile ./$NAME-$VERSION
cp Makefile.$OS bddscout.map ./$NAME-$VERSION
cp CHANGES ./$NAME-$VERSION/CHANGES_bddscout
cp example.bf ./$NAME-$VERSION
cp example.bdd ./$NAME-$VERSION
mkdir ./$NAME-$VERSION/create
cp ./create/*.tcl ./$NAME-$VERSION/create
mkdir ./$NAME-$VERSION/scripts
cp ./scripts/*.tcl ./$NAME-$VERSION/scripts

cd ./$NAME-$VERSION
make package -f Makefile.$OS "CFLAGS = $CFLAGS" "BIDDYDIR = ." "BIDDYLIB = ." "BIDDYLIBEXT = $osbiddylibext" "BINDIR = ."
make clean "BINDIR = ."
rm -f ./biddy.h
rm -f ./libbiddy.a

# source code is not included in the package
rm -f ./bddscout.h
rm -f ./bddscout.c
rm -f ./bddscout.map
rm -f ./bddscoutMain.c
rm -f ./bddscoutDecls.h
rm -f ./bddscoutStubInit.c
rm -f ./bddscoutStubLib.c
rm -f ./bddscoutIFIP.c
rm -f ./bddscoutBRA.c
rm -f ./bddscoutBDDTRACES.c
rm -f ./bddtraces-BIDDY.c

cd ..
cp COPYING ./$NAME-$VERSION
cp README ./$NAME-$VERSION
cp README.$OS ./$NAME-$VERSION
echo "*** BDD Scout OK."

echo "Creating $NAME-$VERSION-$OS.zip ..."
zip -o "$NAME-$VERSION-$OS.zip" ./$NAME-$VERSION/*
zip -o "$NAME-$VERSION-$OS.zip" ./$NAME-$VERSION/create/*
zip -o "$NAME-$VERSION-$OS.zip" ./$NAME-$VERSION/scripts/*
zip -o "$NAME-$VERSION-$OS.zip" IFIP/*
zip -o "$NAME-$VERSION-$OS.zip" IFIP/*/*
zip -o "$NAME-$VERSION-$OS.zip" BDDTRACES/*

rm -fr ./$NAME-$VERSION

echo ""
echo "*******************"
echo "PACKAGES COMPLETED!"
echo "*******************"
echo ""
